<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jamie Pantazi Esmond">
<meta name="dcterms.date" content="2023-05-28">

<title>Jamie Pantazi Esmond - Prisoners of a Broken System</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>
    .quarto-title-block .quarto-title-banner {
      color: #744FC6;
    }
    </style>

<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Jamie Pantazi Esmond</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../abolition/abolition.html">
 <span class="menu-text">Abolition</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../immigration/immigration.html">
 <span class="menu-text">Immigration</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../history/history.html">
 <span class="menu-text">History</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../misc/misc.html">
 <span class="menu-text">Miscellaneous</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resume.html">
 <span class="menu-text">Resume</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Prisoners of a Broken System</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title d-none d-lg-block">Prisoners of a Broken System</h1>
            <p class="subtitle lead">Investigating the Relationship Between High Imprisonment Rates and Access to Inpatient Mental Health Care in Maryland</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Jamie Pantazi Esmond </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 28, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../abolition/Geography_of_Mass_Incarceration.html" class="sidebar-item-text sidebar-link active">Prisoners of a Broken System</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../abolition/prisontowns.html" class="sidebar-item-text sidebar-link">Empty Promises of Prosperity</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../immigration/detention.html" class="sidebar-item-text sidebar-link">Ending Immigrant Detention in the United States</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../history/elias.html" class="sidebar-item-text sidebar-link">Elias Boudinot</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../history/badmen.html" class="sidebar-item-text sidebar-link">Constructing Bad Men</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#prison-gerrymandering" id="toc-prison-gerrymandering" class="nav-link" data-scroll-target="#prison-gerrymandering">Prison Gerrymandering</a></li>
  <li><a href="#mental-health-crime-and-imprisonment" id="toc-mental-health-crime-and-imprisonment" class="nav-link" data-scroll-target="#mental-health-crime-and-imprisonment">Mental Health, Crime, and Imprisonment</a></li>
  </ul></li>
  <li><a href="#data-origins-and-background" id="toc-data-origins-and-background" class="nav-link" data-scroll-target="#data-origins-and-background">Data Origins and Background</a>
  <ul class="collapse">
  <li><a href="#prison-policy-initiative" id="toc-prison-policy-initiative" class="nav-link" data-scroll-target="#prison-policy-initiative">Prison Policy Initiative</a></li>
  <li><a href="#us-census-data" id="toc-us-census-data" class="nav-link" data-scroll-target="#us-census-data">US Census Data</a></li>
  <li><a href="#substance-abuse-and-mental-health-services-administration" id="toc-substance-abuse-and-mental-health-services-administration" class="nav-link" data-scroll-target="#substance-abuse-and-mental-health-services-administration">Substance Abuse and Mental Health Services Administration</a></li>
  <li><a href="#american-community-survey" id="toc-american-community-survey" class="nav-link" data-scroll-target="#american-community-survey">American Community Survey</a></li>
  <li><a href="#the-raw-data" id="toc-the-raw-data" class="nav-link" data-scroll-target="#the-raw-data">The Raw Data</a></li>
  </ul></li>
  <li><a href="#getting-an-analytic-dataset" id="toc-getting-an-analytic-dataset" class="nav-link" data-scroll-target="#getting-an-analytic-dataset">Getting an Analytic Dataset</a>
  <ul class="collapse">
  <li><a href="#merging" id="toc-merging" class="nav-link" data-scroll-target="#merging">Merging</a>
  <ul class="collapse">
  <li><a href="#census-tracts" id="toc-census-tracts" class="nav-link" data-scroll-target="#census-tracts">Census Tracts</a></li>
  <li><a href="#mental-health-facilities" id="toc-mental-health-facilities" class="nav-link" data-scroll-target="#mental-health-facilities">Mental Health Facilities</a></li>
  </ul></li>
  <li><a href="#cleaning" id="toc-cleaning" class="nav-link" data-scroll-target="#cleaning">Cleaning</a></li>
  <li><a href="#manipulating" id="toc-manipulating" class="nav-link" data-scroll-target="#manipulating">Manipulating</a></li>
  <li><a href="#aggregating" id="toc-aggregating" class="nav-link" data-scroll-target="#aggregating">Aggregating</a></li>
  </ul></li>
  <li><a href="#analysis-of-the-data" id="toc-analysis-of-the-data" class="nav-link" data-scroll-target="#analysis-of-the-data">Analysis of the Data</a>
  <ul class="collapse">
  <li><a href="#overall" id="toc-overall" class="nav-link" data-scroll-target="#overall">Overall</a></li>
  <li><a href="#race-and-income" id="toc-race-and-income" class="nav-link" data-scroll-target="#race-and-income">Race and Income</a></li>
  <li><a href="#access-to-mental-health-care" id="toc-access-to-mental-health-care" class="nav-link" data-scroll-target="#access-to-mental-health-care">Access to Mental Health Care</a></li>
  </ul></li>
  <li><a href="#discussion-and-conclusion" id="toc-discussion-and-conclusion" class="nav-link" data-scroll-target="#discussion-and-conclusion">Discussion and Conclusion</a>
  <ul class="collapse">
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#further-research" id="toc-further-research" class="nav-link" data-scroll-target="#further-research">Further Research</a>
  <ul class="collapse">
  <li><a href="#datasets" id="toc-datasets" class="nav-link" data-scroll-target="#datasets">Datasets:</a></li>
  </ul></li>
  <li><a href="#policy-implications" id="toc-policy-implications" class="nav-link" data-scroll-target="#policy-implications">Policy Implications</a></li>
  </ul></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">Appendix</a>
  <ul class="collapse">
  <li><a href="#r-code" id="toc-r-code" class="nav-link" data-scroll-target="#r-code">R Code</a></li>
  <li><a href="#excel-formulas" id="toc-excel-formulas" class="nav-link" data-scroll-target="#excel-formulas">Excel Formulas</a></li>
  <li><a href="#arcgis-pro-log" id="toc-arcgis-pro-log" class="nav-link" data-scroll-target="#arcgis-pro-log">ArcGIS Pro Log</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div style="page-break-after: always;"></div>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>As the Prison Industrial Complex has expanded, scholars have examined the relationship between place and imprisonment in terms of places with high rates of reported crime, places with an overwhelming police presence, and the experiences of people in those communities and their relationship with law enforcement and the greater criminal justice system. It has been well documented that people of color, especially Black men, are more likely to become involved with the carceral system in the US <span class="citation" data-cites="simesPunishingPlacesGeography2021 easonMassImprisonmentRuralUrban2017 pettitMassImprisonmentLife2004 sharkeyStuckPlaceUrban2013">(<a href="#ref-easonMassImprisonmentRuralUrban2017" role="doc-biblioref">Eason et al., 2017</a>; <a href="#ref-pettitMassImprisonmentLife2004" role="doc-biblioref">Pettit &amp; Western, 2004</a>; <a href="#ref-sharkeyStuckPlaceUrban2013" role="doc-biblioref">Sharkey, 2013</a>; <a href="#ref-simesPunishingPlacesGeography2021" role="doc-biblioref">Simes, 2021</a>)</span>. Other than race, class is the next predominant factor that has been addressed by previous research; while race and class are inextricably intertwined, class conditions that lead to imprisonment stretch beyond the urban and racial factors usually associated with crime and subjugation <span class="citation" data-cites="pettitMassImprisonmentLife2004 easonMassImprisonmentRuralUrban2017">(<a href="#ref-easonMassImprisonmentRuralUrban2017" role="doc-biblioref">Eason et al., 2017</a>; <a href="#ref-pettitMassImprisonmentLife2004" role="doc-biblioref">Pettit &amp; Western, 2004</a>)</span>. The removal of individuals from an already struggling community only contributes to the cycle of instability that leads to crime and harm. These individuals are fathers, workers, caregivers, and other valuable members of their community; ripping them from their families not only impacts those who may have violated the law, but those they leave behind who may have been financially or emotionally dependent on them <span class="citation" data-cites="gilmoreGoldenGulagPrisons2007">(<a href="#ref-gilmoreGoldenGulagPrisons2007" role="doc-biblioref">Gilmore, 2007</a>)</span>.</p>
<p>By using what is already known about the disparities in crime and punishment to investigate whether imprisonment is a viable solution to the harm caused by crime, questions about the prevention of crime and the reduction of harm can be answered. What are other similarities of places with high imprisonment rates that could be addressed to reduce imprisonment and aid the reintegration of those released back to their communities? While it may be impossible to determine if the shared characteristics of these locations are the <em>cause</em> of high rates of imprisonment, the <em>result</em>, or both, it is important to assess how these characteristics illuminate a piece of the greater influence of oppressive policies that fuel the Prison Industrial Complex as a whole.</p>
<section id="prison-gerrymandering" class="level2">
<h2 class="anchored" data-anchor-id="prison-gerrymandering">Prison Gerrymandering</h2>
<p>Prison gerrymandering is the practice of counting imprisoned people as residents of the place where they are imprisoned. The US Census defines residence as “where they live and sleep most of the time” <span class="citation" data-cites="uscensusbureau2020CensusResidence2018">(<a href="#ref-uscensusbureau2020CensusResidence2018" role="doc-biblioref">US Census Bureau, 2018</a>)</span>. However, incarcerated people cannot vote or participate in the community where they are detained, and they often maintain ties to their community of origin and hope to have a future there when they return. The practice of counting these people as part of a community in which they have no role not only boosts representation for people around a prison but siphons resources and representation from their home communities <span class="citation" data-cites="benvenisteWhatPrisonGerrymandering2022">(<a href="#ref-benvenisteWhatPrisonGerrymandering2022" role="doc-biblioref">Benveniste, 2022</a>)</span>. The community conditions of places with high imprisonment rates are viewed as both the cause and the consequence of over-policing and disenfranchisement through the Prison Industrial Complex as it has expanded in the last several decades. As more people are pulled away from their homes and counted in a place that does not value their interests, the barriers to opportunity are reinforced, and the cycle of subjugation continues. If the true purpose of imprisonment is rehabilitation, and the hope upon release is to participate in society fully, the interests and opportunities of these individuals should be considered by policymakers who will impact their future opportunities for success.</p>
<p>As of 2021, about a dozen states had ended prison gerrymandering which would impact the redistricting from the 2020 Census <span class="citation" data-cites="fensterHowManyStates2021">(<a href="#ref-fensterHowManyStates2021" role="doc-biblioref">Fenster, 2021</a>)</span>. Because of the details involved with determining where and how to count these individuals in their home communities, data has been made available about precisely where people in prison are from, and where they intend to return to <span class="citation" data-cites="widraWherePeoplePrison2023">(<a href="#ref-widraWherePeoplePrison2023" role="doc-biblioref">Widra, 2023</a>)</span>. This information is valuable and unique because it provides a link to determine the conditions that both create an environment where people feel the need to imprison larger portions of the population and create nuanced solutions to reduce both the harm that leads to imprisonment and the harm caused by it.</p>
</section>
<section id="mental-health-crime-and-imprisonment" class="level2">
<h2 class="anchored" data-anchor-id="mental-health-crime-and-imprisonment">Mental Health, Crime, and Imprisonment</h2>
<p>Mental health care is an important resource to ensure overall health and quality of life <span class="citation" data-cites="princeNoHealthMental2007">(<a href="#ref-princeNoHealthMental2007" role="doc-biblioref">Prince et al., 2007</a>)</span>. The expansion of mental health care in the last few decades has been a response to a dire crisis that has long been ignored and stigmatized, and the benefits of access and awareness of mental health services are obvious to many who have utilized these services <span class="citation" data-cites="hortonLaunchingNewMovement2007">(<a href="#ref-hortonLaunchingNewMovement2007" role="doc-biblioref">Horton, 2007</a>)</span>. Though access to mental health services is generally regarded as a positive influence on communities, the marginalized groups who often lack access to these services are the same communities that are targeted for high crime and imprisonment rates <span class="citation" data-cites="saxenaResourcesMentalHealth2007">(<a href="#ref-saxenaResourcesMentalHealth2007" role="doc-biblioref">Saxena et al., 2007</a>)</span>. The link between access to mental health care, crime, and imprisonment is worth investigating to advocate for more resources to be made available for these communities and potentially prevent crime and harm before they happen, and as a result, reduce unnecessary imprisonment.</p>
<p>Three major components of mental health care and its relationship with imprisonment have been discussed. The first is mental health care as prevention of criminal and violent behavior <span class="citation" data-cites="hodginsConsequencesConductDisorder2005 petrasDevelopmentalEpidemiologicalCourses2008 brennanMajorMentalDisorders2000">(<a href="#ref-brennanMajorMentalDisorders2000" role="doc-biblioref">Brennan et al., 2000</a>; <a href="#ref-hodginsConsequencesConductDisorder2005" role="doc-biblioref">Hodgins et al., 2005</a>; <a href="#ref-petrasDevelopmentalEpidemiologicalCourses2008" role="doc-biblioref">Petras et al., 2008</a>)</span>. Increased access to mental health care, especially on a large scale could lead to an overall reduction in violent and aggressive behavior, which comprises most of the crime residents are most concerned about.</p>
<p>The second component is mental health care for the residents impacted by the loss of a loved one or caretaker to imprisonment. Many people in prison are parents or otherwise supportive to other that they leave behind to serve their sentence <span class="citation" data-cites="wangBothSidesBars2022">(<a href="#ref-wangBothSidesBars2022" role="doc-biblioref">Wang, 2022</a>)</span>. The social and economic consequences of mass imprisonment are far-reaching, and the individuals living through those consequences would certainly benefit from a support structure that values their mental health <span class="citation" data-cites="hatzenbuehlerCollateralDamageMass2015 nosratiEconomicDeclineIncarceration2019">(<a href="#ref-hatzenbuehlerCollateralDamageMass2015" role="doc-biblioref">Hatzenbuehler et al., 2015</a>; <a href="#ref-nosratiEconomicDeclineIncarceration2019" role="doc-biblioref">Nosrati et al., 2019</a>)</span>.</p>
<p>Lastly, prison can have a strong psychological impact on a person, and formerly imprisoned people may bring that trauma back to their communities when they are released. People in prison are more likely to suffer from a mental health issue, both because, untreated, they are more likely to be arrested and because of the trauma endured throughout their sentence <span class="citation" data-cites="cloudLifeSupportPublic2014 quandtResearchRoundupIncarceration2021">(<a href="#ref-cloudLifeSupportPublic2014" role="doc-biblioref">Cloud, 2014</a>; <a href="#ref-quandtResearchRoundupIncarceration2021" role="doc-biblioref">Quandt &amp; Jones, 2021</a>)</span>. The damage of imprisonment on mental health can include family disconnection, loss of autonomy and lack of purpose, and unpredictability <span class="citation" data-cites="quandtResearchRoundupIncarceration2021">(<a href="#ref-quandtResearchRoundupIncarceration2021" role="doc-biblioref">Quandt &amp; Jones, 2021</a>)</span>. Accessibility to mental health care may influence productive reintegration after release from prison.</p>
<p>With the new information about the home locations of imprisoned people, there are a number of relationships to investigate. The obvious demographic and economic factors should be considered and potentially controlled in many analyses. One spatial relationship that could be investigated using this data is the accessibility, in terms of distance, to mental health facilities. While there are many dimensions to the concept of accessibility, distance can be a useful indicator of at least when mental health care options are <em>not</em> available. Other dimensions to consider are the capacity of facilities, specific services provided, populations served, payment methods accepted, and outreach or awareness of services available. This analysis focuses on the dimension of physical location and proximity as an indicator of access to mental health care, specifically inpatient care for emergency situations.</p>
</section>
</section>
<section id="data-origins-and-background" class="level1">
<h1>Data Origins and Background</h1>
<p>The data for this analysis comes from four different sources combined to create a versatile basis for geographic analysis of imprisonment and its relationship with location. The imprisonment data is from Prison Policy Initiative, a non-profit organization working to “expose the broader harm of mass criminalization” through data and research <span class="citation" data-cites="prisonpolicyinitiative">(<a href="#ref-prisonpolicyinitiative" role="doc-biblioref">Prison Policy Initiative, n.d.</a>)</span>. The demographic data for the same census tracts is publicly available from the US Census Bureau <span class="citation" data-cites="CensusBureauData2020">(<a href="#ref-CensusBureauData2020" role="doc-biblioref"><em>Census <span>Bureau Data</span></em>, 2020</a>)</span>. Information about mental health facilities is available from the Substance Abuse and Mental Health Services Administration. Though the department provides data about many different aspects of mental health treatment and services, since this analysis is focused on the geography of imprisonment, the <em>2020 National Directory Of Mental Health Treatment Facilities</em> contains locations and key characteristics for all facilities in the US <span class="citation" data-cites="samhsaNationalDirectoryMental2020">(<a href="#ref-samhsaNationalDirectoryMental2020" role="doc-biblioref">SAMHSA, 2020a</a>)</span>. Finally, the American Community Survey hosts geographic and demographic data at the census tract level that is available publicly. This data was used to map the previous data geographically and perform spatial analysis <span class="citation" data-cites="esriACSContextEmergency2020">(<a href="#ref-esriACSContextEmergency2020" role="doc-biblioref">Esri, 2020</a>)</span>.</p>
<section id="prison-policy-initiative" class="level2">
<h2 class="anchored" data-anchor-id="prison-policy-initiative">Prison Policy Initiative</h2>
<p>The data gathered from the Prison Policy Initiative is cross-sectional data based on data from the 2020 Census and Maryland state data. The data originated as administrative data from the Maryland Department of Public Safety and Correctional Services and was combined with population data from the Census. The Prison Policy Initiative collected, calculated, and combined this data for public use for various levels of geography for Maryland and eleven other states where prison gerrymandering has been overruled.</p>
<p>Most of this data is from the 2020 Census. The imprisonment rate used the redistricting data from Maryland’s law ending prison gerrymandering to count prisoners as residents of their home neighborhoods instead of the location of the prison. The data was compiled using the data from the Maryland Department of Public Safety and Correctional Services which provided the home addresses of imprisoned people to redistricting officials to report them to the Census so they would be recorded in their home neighborhoods and not the prison’s location <span class="citation" data-cites="widraWherePeoplePrison2023 RedistrictingData2020">(<a href="#ref-RedistrictingData2020" role="doc-biblioref"><em>Redistricting <span>Data</span></em>, 2020</a>; <a href="#ref-widraWherePeoplePrison2023" role="doc-biblioref">Widra, 2023</a>)</span>.</p>
<p>The original data had 1475 observations and the following 6 variables: FIPS code 2020, Maryland Census tracts, Number of people in state prison from each Census tract 2020, Census population 2020, Total population 2020, and Imprisonment rate per 100,000. The unit of observation for this analysis is the Census tract.</p>
<p>This data can be used to identify what characteristics are common among places with high imprisonment rates. Combined with demographic data about these locations and the proximity of mental health resources, this data can highlight areas in need of more mental health resources to reduce the harm caused by imprisonment and over-policing.</p>
<p>The original data is available from the Prison Policy Initiative website where the report was published. The census tract data for Maryland was copied into Excel, and the variables were renamed to be more usable in the analysis <span class="citation" data-cites="thejusticepolicyinstituteCensusTractAppendix2023">(<a href="#ref-thejusticepolicyinstituteCensusTractAppendix2023" role="doc-biblioref">The Justice Policy Institute &amp; Prison Policy Initiative, 2023</a>)</span>. The Prison Policy Initiative report provides thorough documentation of the data, its origins, and how it was processed. The variables have meaningful names, so there is no need for an official codebook.</p>
<p>The abolition of prison gerrymandering is still ongoing, so this data is only available in limited locations. However, it can be used to shed a light on the issue of prison gerrymandering and identify the common circumstances of places with high imprisonment rates.</p>
</section>
<section id="us-census-data" class="level2">
<h2 class="anchored" data-anchor-id="us-census-data">US Census Data</h2>
<p>The US Census collects cross-sectional data every ten years and makes it available publicly. Though the Census collects data about many different attributes at the individual and household level, the data for this analysis is aggregated to the census tract level. Four datasets were acquired from the online Census repository <span class="citation" data-cites="CensusBureauData2020">(<a href="#ref-CensusBureauData2020" role="doc-biblioref"><em>Census <span>Bureau Data</span></em>, 2020</a>)</span>. These included the following attributes: Employment (2020) with 1475 observations and 562 variables about employment rates; Geographic Mobility (2020) with 1475 observations and 1122 variables containing general demographic information about the population of each tract along with records of what types of people moved within and from outside the county, state, and country; Median Income (2020) with 1475 observations and 483 variables about the median income in each tract for different demographic groups; and Urban and Rural (2010) with 1406 observations and 9 variables contains the number of households in rural and urban areas.</p>
<p>In combination with the imprisonment data, the census data can show correlations between the racial and socioeconomic characteristics of an area and the rate of imprisonment. As stated earlier, while this may not be enough to prove causation, it does describe the systematic ways that incarceration and the Prison Industrial Complex as a whole impact people of color and low-income communities disproportionately.</p>
<p>The data was originally downloaded from the US Census website as a compressed file with three CSV files <span class="citation" data-cites="CensusBureauData2020">(<a href="#ref-CensusBureauData2020" role="doc-biblioref"><em>Census <span>Bureau Data</span></em>, 2020</a>)</span>. One file contained the data, another file contained the variable descriptions for each coded variable in the data file. The third file contained notes about the data and documentation about the methods used to collect and distribute the data. The US Census is a respected source for basic demographic information about each census tract. This is important to determine disparities in different areas that are linked to racial and socioeconomic status.</p>
</section>
<section id="substance-abuse-and-mental-health-services-administration" class="level2">
<h2 class="anchored" data-anchor-id="substance-abuse-and-mental-health-services-administration">Substance Abuse and Mental Health Services Administration</h2>
<p>Within the US Department of Health and Human Services, the Substance Abuse and Mental Health Services Administration collects and provides data about a wide array of treatments, services, and facilities for mental health and substance abuse <span class="citation" data-cites="samhsaSubstanceAbuseMental">(<a href="#ref-samhsaSubstanceAbuseMental" role="doc-biblioref">SAMHSA, n.d.</a>)</span>. The data used for this specific analysis contains geographic and key characteristics of mental health facilities in Maryland. While some of these facilities also provide substance abuse treatment, facilities that exclusively provide substance abuse treatment are not included in this directory. The information about each facility is collected by a survey at the facility level; many data points are collected in the survey about specific treatments and capacities, but the information provided with geographic information in this directory only contained basic characteristics about the type of care, settings, operation, payments accepted, populations served, and others. Altogether, the <em>National Directory of Mental Health Treatment Facilities 2020</em> provides a code for 103 different attributes for 235 facilities in Maryland <span class="citation" data-cites="samhsaNationalDirectoryMental2020">(<a href="#ref-samhsaNationalDirectoryMental2020" role="doc-biblioref">SAMHSA, 2020a</a>)</span>.</p>
<p>The information is provided in a PDF available to download. Since the data is not available in a format that is easily analyzed, the information needed to be extracted and separated into a readable format for analysis. Each facility is listed with a name, address, and code for each attribute associated with that facility. The directory contains a key at the beginning to interpret each code.</p>
<p>The locations and services provided by each facility can demonstrate how access and proximity may be related to the rate of imprisonment in a community. People in jails and prisons are more likely than the general population to suffer from a serious mental health issue, and the carceral system does the bare minimum to provide resources and health care to these individuals while they are incarcerated, let alone before and after their imprisonment <span class="citation" data-cites="cloudLifeSupportPublic2014">(<a href="#ref-cloudLifeSupportPublic2014" role="doc-biblioref">Cloud, 2014</a>)</span>. The availability of mental health treatment, and especially inpatient treatment for individuals who may be a risk to the community, as an alternative to imprisonment has more potential to increase public safety and the well-being of communities.</p>
</section>
<section id="american-community-survey" class="level2">
<h2 class="anchored" data-anchor-id="american-community-survey">American Community Survey</h2>
<p>The American Community Survey (ACS) continuously collects data about many different variables to create estimates about the social, economic, and demographic characteristics of different communities. As part of the US Census, these data are available from the census bureau directly. However, for spatial analysis the ACS and Esri, a leader in geographic information system (GIS) software, host spatial data along with various attributes from the survey <span class="citation" data-cites="esriACSContextEmergency2020">(<a href="#ref-esriACSContextEmergency2020" role="doc-biblioref">Esri, 2020</a>)</span>.</p>
<p>The Context for Emergency Response feature layer contains 1475 records for Maryland with 89 variables including the coordinates and shapes required to visually represent attributes geographically at the census tract level. Information about factors that relate to emergency response includes the amount of the population without health insurance, internet access at home, or a personal vehicle. The website hosting the data provides metadata and details about each variable available.</p>
<p>While the importance of these data for this analysis is primarily spatial, the variables about some of these characteristics could be useful for further research to identify other relationships with imprisonment rates of different communities. The spatial data for the census tracts can also be used to determine the distance to different types of mental health facilities.</p>
</section>
<section id="the-raw-data" class="level2">
<h2 class="anchored" data-anchor-id="the-raw-data">The Raw Data</h2>
<p>When acquiring observational data collected by another organization, there are limitations on what is available. Often a dataset will include many additional variables in addition to the variables required to answer a research question.</p>
<p>The data from the Prison Policy Initiative was already normalized and estimated in relation to population data from the Census. Because this element was already processed and calculated, there are no missing values. Several outliers exist because of extremely low populations of several census tracts, the imprisonment of only one resident shows as a high proportion when normalized at a rate per 100,000 residents.</p>
<p>The US Census provides hundreds of attributes at the census tract level, however, these are often raw counts of individuals or households for each category. The estimates must be divided by the total counts to calculate the percentage of the population for each census tract for equal comparison. As with many large repositories of data, these datasets are missing some values for various variables. For the useful variables missing values, they are scarce and random; the values can easily be imputed for the important variables by finding the mean within the county of the tract. While outliers may exist in some categories, none were prominent in the variables selected for analysis. The values for each variable are numbers (with the exception of the geographic identifier and the name of the tract), however, they are not always stored as numbers and will need to be properly formatted.</p>
<p>The data about mental health facilities came from the <em>National Directory of Mental Health Treatment Facilities 2020</em> as part of the Behavioral Health Services Information System Series <span class="citation" data-cites="samhsaNationalDirectoryMental2020">(<a href="#ref-samhsaNationalDirectoryMental2020" role="doc-biblioref">SAMHSA, 2020a</a>)</span>. Since the data is in PDF format, the information needs to be extracted and parsed into an analytic format. Each facility name is accompanied by abbreviated codes that need to be converted into dummy variables. Since this is a comprehensive list of facilities, there are no missing values. The values for facility name and address are strings and do not need to be formatted; however, the address values will be used to obtain the geographic data about their locations on a map and in relation to each census tract.</p>
<p>The spatial data from the ACS is available from the Living Atlas with variables for both the raw counts and the percentages for each attribute as a feature layer for use in ArcGIS Pro <span class="citation" data-cites="LivingAtlasWorld">(<a href="#ref-LivingAtlasWorld" role="doc-biblioref"><em>Living <span>Atlas</span> of the <span>World</span></em>, n.d.</a>)</span>. The data did contain some missing values, but only in three observations and for variables not used for this analysis. Since the data came from a curated source, it was properly formatted as the appropriate data type for both spatial and quantitative analysis.</p>
</section>
</section>
<section id="getting-an-analytic-dataset" class="level1">
<h1>Getting an Analytic Dataset</h1>
<p>All of the raw data collected contains some kind of missing values, unneeded variables, and may be in different formats. To create an analytic dataset, each dataset must be merged, cleaned, and manipulated to answer the research question and provide a useful new dataset for future analysis. The unit of analysis for this research is the census tract, but several key variables have been aggregated at the county level for comparison.</p>
<section id="merging" class="level2">
<h2 class="anchored" data-anchor-id="merging">Merging</h2>
<section id="census-tracts" class="level3">
<h3 class="anchored" data-anchor-id="census-tracts">Census Tracts</h3>
<p>The imprisonment rate data was merged with several tables from the US Census. These were almost all an exact match because each census tract has a unique identifier to link it to the data from other datasets. The exception was for the Urban and Rural data because that was only available from 2010 which had fewer tracts than the 2020 data. The 2010 Urban and Rural census data was joined with 2010 census tract shapefiles in ArcGIS Pro. The spatial data was then apportioned to 2020 tracts based on the area of overlap and weighted by population.</p>
<p>After merging the census data with the imprisonment data, the variables with relevant values were extracted to remove unneeded information regarding annotations and margins of error. The remaining variables were renamed with more meaningful names to better reflect the meaning of the values.</p>
<p>The merged data from the Prison Policy Initiative and the Census were joined to the ACS tracts in ArcGIS Pro for mapping. Several variables from ACS Context for Emergency Response were added to the merged dataset including percent less than 18 years old, percent 65 Years and over, percent in dependent age groups (under 18 and 65+), percent of households with no vehicle available, percent with a disability, percent with Medicaid coverage, percent with Medicare coverage, percent with no health insurance coverage, percent without a smartphone, and percent without internet access at home. The new variables were renamed with more meaningful names to better reflect the meaning of the values.</p>
</section>
<section id="mental-health-facilities" class="level3">
<h3 class="anchored" data-anchor-id="mental-health-facilities">Mental Health Facilities</h3>
<p>After extraction from the directory, the dummy variables for mental health facilities in Maryland were renamed with meaningful names, and the addresses for each facility were geocoded in ArcGIS Pro. The geocoded facilities were also joined the newly merged data by spatial proximity. The distance to the closest mental health facility from the edge of each tract was calculated in ArcGIS Pro in feet (as the crow flies) and then converted to miles. The dummy variables for the closest facility were also added to the dataset. This process was repeated for distance to the closest inpatient mental health facility, the closest inpatient facility providing crisis intervention, and the closest inpatient facility accepting walk-ins. Using ArcGIS, the total driving distance in miles and minutes was also calculated from the geographic center of each tract to the closest facility in each of these categories.</p>
<p>The complete dataset includes the imprisonment rate values from the Prison Policy Initiative, the selected attributes from the various Census and ACS tables, and the name, address, and dummy variables for the closest mental health facility, the closest inpatient facility, the closest inpatient facility with crisis intervention, and the closest inpatient facility accepting walk-ins, along with the linear distance, driving distance, and driving time to these facilities. These facility attributes were chosen because they represent opportunities for an alternative response to a dangerous situation that may be better resolved with mental health treatment than law enforcement and imprisonment. If individuals who are imprisoned were able to access mental health treatment, and especially inpatient treatment if they may be a threat, in a time of crisis instead of being forced into the stressful and prejudiced criminal justice system, immediate and long-term harm could be avoided.</p>
</section>
</section>
<section id="cleaning" class="level2">
<h2 class="anchored" data-anchor-id="cleaning">Cleaning</h2>
<p>Most of the data collected was mostly clean. A few missing values, misformatted values, and outliers needed to be dealt with. By visually analyzing the raw data, sanity checks, and validation, these issues were identified and resolved. In the imprisonment data, some of the total population values were miscalculated and were manually changed by adding the number of imprisoned individuals to the Census population values in Excel.</p>
<p>Census data contains many variables that describe both the attributes and the accuracy of the attribute’s values. Many of these attributes were removed altogether, and for others, only the annotation variables were removed, leaving only the relevant variables. Some of the relevant variables were formatted incorrectly and needed to be converted to a numeric format. Several variables contained missing values, and these were imputed with the mean value of that variable for the tract’s county. The observations with imputed values are identifiable through a new variable indicating whether they had missing values. The last issue with these data was outliers. Because the imprisonment rate is calculated per 100,000 residents, census tracts with extremely low populations may have an extremely high imprisonment rate, even if only one person is from that tract. To resolve this issue, all tracts with less than 100 total population were excluded. Most of these tracts also had very little land area, and their absence should not impact the results. Three additional tracts were dropped due to missing values for several variables. The three tracts were missing values because they are tracts that only contain corrections facilities, the Baltimore jail, the Maryland correctional training center, and the Maryland state prison</p>
<p>The ACS data also contained some missing values. Three additional tracts were dropped due to missing values for several ACS variables. The three tracts were missing values because they are tracts that only contain correctional facilities, the Baltimore jail, the Maryland correctional training center, and the Maryland state prison. The total number of observations remaining after cleaning the data fell to 1455 census tracts from the original 1475.</p>
</section>
<section id="manipulating" class="level2">
<h2 class="anchored" data-anchor-id="manipulating">Manipulating</h2>
<p>Once the complete dataset had been merged and cleaned, some new variables were created to better represent the data for interpretation. Several of the census variables were converted from raw counts to percentages by dividing the counts by the total and multiplying by 100. These new variables include percent Black, White, and other race; the percent with no high school diploma, only a high school diploma, some college, bachelor’s degree, and advanced degree (bachelor’s and advanced degree was also combined to have the percent of the population with at least a bachelor’s degree); percent under the poverty level; and percent of households who own and rent.</p>
<p>Some of the new percent variables were further converted into dummy variables to represent tracts with either a majority or a value above or below the average. The Black and White ratios were converted into majority dummy variables; the same was done for the homeownership and renters variables. The percent of the tract with a bachelor’s degree or higher, percent under poverty, and the unemployment rate were converted to variables to indicate if the value was above or below the mean. Each of these variables was also converted into categorical variables with descriptive labels.</p>
<p>In order to be able to perform analysis at the county level as well as the tract level, the county name was extracted from the tract name variable. The new variable would contain only the name of the county. Because of a formatting error with the apostrophes in some of the county names, some of the values needed to be manually cleaned in Excel.</p>
</section>
<section id="aggregating" class="level2">
<h2 class="anchored" data-anchor-id="aggregating">Aggregating</h2>
<p>To assess the values for each tract in relation to the county they are governed by, the mean values for selected variables were aggregated to the county level. The variables aggregated include the imprisonment rate, median income, and unemployment rate. The following percent variables were also aggregated: percent Black, percent White, percent with a bachelor’s degree or higher, percent under the poverty level, percent of residents who own their home, and percent of residents who rent. Once the averages for each county were calculated, the county values were added to the observation for each tract for simpler analysis.</p>
</section>
</section>
<section id="analysis-of-the-data" class="level1">
<h1>Analysis of the Data</h1>
<p>With all the variables together in one dataset, census tracts and mental health facilities can be compared using a variety of characteristics. Not only is the final dataset free of missing values and unusual census tracts, the analytic dataset has various general characteristics for each tract. Each tract is also linked to the closest mental health facilities offering several specific services. The census tract FIPS (Federal Information Processing Standards) codes remain in the dataset so additional variable can easily be added. Instead of several datasets in different formats with specific information, the full and unique dataset can now help describe different characteristics and dimensions of high rates of imprisonment.</p>
<div class="cell" data-tbl-align="center">
<div class="cell-output-display">
<div id="tbl-sumMD1" class="anchored">

<table><caption>Table&nbsp;1:  Census Tract Characteristics </caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> Mean </th>
   <th style="text-align:center;"> Median </th>
   <th style="text-align:center;"> Std.Dev </th>
   <th style="text-align:center;"> Min </th>
   <th style="text-align:center;"> Max </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;background-color: #F4A5FA !important;"> Imprisonment Rate per 100,000 </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4em; "> 307 </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4em; "> 136 </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4em; "> 493 </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4em; "> 0 </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4em; "> 3,767 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total Population </td>
   <td style="text-align:center;width: 4em; "> 4,248 </td>
   <td style="text-align:center;width: 4em; "> 4,049 </td>
   <td style="text-align:center;width: 4em; "> 1,701 </td>
   <td style="text-align:center;width: 4em; "> 621 </td>
   <td style="text-align:center;width: 4em; "> 15,052 </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;"> Median Income </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> $92,743 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> $87,231 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> $41,756 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> $10,391 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> $250,000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> % Black </td>
   <td style="text-align:center;width: 4em; "> 31.9% </td>
   <td style="text-align:center;width: 4em; "> 19.3% </td>
   <td style="text-align:center;width: 4em; "> 30.8% </td>
   <td style="text-align:center;width: 4em; "> 0.0% </td>
   <td style="text-align:center;width: 4em; "> 99.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;"> % with Bachelor's Degree </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 39.9% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 37.2% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 20.7% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 1.6% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 95.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> % Under Poverty Level </td>
   <td style="text-align:center;width: 4em; "> 10.0% </td>
   <td style="text-align:center;width: 4em; "> 7.2% </td>
   <td style="text-align:center;width: 4em; "> 9.5% </td>
   <td style="text-align:center;width: 4em; "> 0.0% </td>
   <td style="text-align:center;width: 4em; "> 86.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;"> Unemployment Rate </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 5.4% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 4.5% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 3.9% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 0.0% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 31.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> % Renter-Occupied Housing </td>
   <td style="text-align:center;width: 4em; "> 32.1% </td>
   <td style="text-align:center;width: 4em; "> 25.1% </td>
   <td style="text-align:center;width: 4em; "> 24.3% </td>
   <td style="text-align:center;width: 4em; "> 0.0% </td>
   <td style="text-align:center;width: 4em; "> 100% </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;"> % with Disability </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 11.7% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 10.5% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 5.7% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 0.4% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 41.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> % with Medicaid </td>
   <td style="text-align:center;width: 4em; "> 14.4% </td>
   <td style="text-align:center;width: 4em; "> 11.5% </td>
   <td style="text-align:center;width: 4em; "> 11.1% </td>
   <td style="text-align:center;width: 4em; "> 0.0% </td>
   <td style="text-align:center;width: 4em; "> 64.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;"> % with Medicare </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 4.2% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 3.6% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 2.9% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 0.0% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 23.0% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> % with No Health Insurance </td>
   <td style="text-align:center;width: 4em; "> 6.0% </td>
   <td style="text-align:center;width: 4em; "> 4.4% </td>
   <td style="text-align:center;width: 4em; "> 5.5% </td>
   <td style="text-align:center;width: 4em; "> 0.0% </td>
   <td style="text-align:center;width: 4em; "> 58.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;"> % Rural </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 13.1% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 0.0% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 28.7% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 0.0% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 100% </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p><a href="#tbl-sumMD1">Table&nbsp;1</a> summarizes some key variables regarding census tract characteristics in the new dataset. The median income across all tracts in Maryland was $87,231, compared to a national median income of $62,529. The average percentage of Black residents for each tract was 31.9%, compared to only 11.2% nationwide. The average rate of individuals on Medicaid in Maryland is lower than the national average at 14.4%, compared to 19.9%. As a midatlantic state, tracts in Maryland have a lower percentage of rural housing than the national average by about half, 13.1% and 27%, respectively.</p>
<div class="cell" data-tbl-align="center">
<div class="cell-output-display">
<div id="tbl-distance" class="anchored">

<table style="NAborder-bottom: 0;"><caption>Table&nbsp;2:  Distance to Nearest Inpatient Facility </caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> Mean </th>
   <th style="text-align:center;"> Median </th>
   <th style="text-align:center;"> Std.Dev </th>
   <th style="text-align:center;"> Min </th>
   <th style="text-align:center;"> Max </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;width: 20em; "> Miles to Mental Health Facility* </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 1.8 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4.5em; "> 0.8 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 3.0 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 0.0 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 33.2 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 20em; "> Travel Time to Mental Health Facility </td>
   <td style="text-align:center;width: 3.5em; "> 9 min </td>
   <td style="text-align:center;width: 4.5em; "> 7 min </td>
   <td style="text-align:center;width: 3.5em; "> 7 min </td>
   <td style="text-align:center;width: 3.5em; "> 0 min </td>
   <td style="text-align:center;width: 4em; "> 76 min </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;width: 20em; "> Driving Miles to Mental Health Facility </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 4.4 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4.5em; "> 2.7 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 5.4 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 0.1 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 63.2 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 20em; "> Miles to Inpatient Facility* </td>
   <td style="text-align:center;width: 3.5em; "> 6.6 </td>
   <td style="text-align:center;width: 4.5em; "> 5.1 </td>
   <td style="text-align:center;width: 3.5em; "> 6.1 </td>
   <td style="text-align:center;width: 3.5em; "> 0.0 </td>
   <td style="text-align:center;width: 4em; "> 37.7 </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;width: 20em; "> Travel Time to Inpatient Facility </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 19 min </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4.5em; "> 17 min </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 12 min </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 2 min </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 92 min </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 20em; "> Driving Miles to Inpatient Facility </td>
   <td style="text-align:center;width: 3.5em; "> 11.2 </td>
   <td style="text-align:center;width: 4.5em; "> 9.1 </td>
   <td style="text-align:center;width: 3.5em; "> 9.6 </td>
   <td style="text-align:center;width: 3.5em; "> 0.3 </td>
   <td style="text-align:center;width: 4em; "> 68.3 </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;width: 20em; "> Miles to Inpatient Facility w/ Crisis Intervention* </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 10.1 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4.5em; "> 6.5 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 12.3 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 0.0 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 85.6 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 20em; "> Travel Time to Inpatient Facility w/ Crisis Intervention </td>
   <td style="text-align:center;width: 3.5em; "> 26 min </td>
   <td style="text-align:center;width: 4.5em; "> 19 min </td>
   <td style="text-align:center;width: 3.5em; "> 27 min </td>
   <td style="text-align:center;width: 3.5em; "> 2 min </td>
   <td style="text-align:center;width: 4em; "> 175 min </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;width: 20em; "> Driving Miles to Inpatient Facility w/ Crisis Intervention </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 17.7 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4.5em; "> 10.9 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 23.9 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 0.3 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 151.9 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 20em; "> Miles to Inpatient Facility accepting Walk-ins* </td>
   <td style="text-align:center;width: 3.5em; "> 9.6 </td>
   <td style="text-align:center;width: 4.5em; "> 5.9 </td>
   <td style="text-align:center;width: 3.5em; "> 14.0 </td>
   <td style="text-align:center;width: 3.5em; "> 0.0 </td>
   <td style="text-align:center;width: 4em; "> 90.0 </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;width: 20em; "> Travel Time to Inpatient Facility accepting Walk-ins </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 24 min </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4.5em; "> 18 min </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 26 min </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 3.5em; "> 2 min </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 4em; "> 161 min </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 20em; "> Driving Miles to Inpatient Facility accepting Walk-ins </td>
   <td style="text-align:center;width: 3.5em; "> 16.3 </td>
   <td style="text-align:center;width: 4.5em; "> 10.0 </td>
   <td style="text-align:center;width: 3.5em; "> 23.3 </td>
   <td style="text-align:center;width: 3.5em; "> 0.3 </td>
   <td style="text-align:center;width: 4em; "> 140.8 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">*</span> <sup></sup> as the crow flies</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>The key additional variables calculated and added to the dataset are the distances from each census tract to the closest mental health facility with various characteristics. By identifying various measures of access by distance for each tract, this new dataset may offer unique insights about which communities are most in need of investment in mental health well-being and crisis response. As seen in <a href="#tbl-distance">Table&nbsp;2</a>, the average distance throughout the state is not extreme; the average travel time to any facility is less than ten minutes, and under thirty minutes to inpatient facilities with crisis intervention or who accept walk-in patients. However, some tracts are up to 76 minutes away for any mental health facility, 92 minutes for inpatient facilities, and up to almost three hours for an inpatient facility with crisis intervention. For communities in these areas, the only available response to crisis may be the police, which can lead to more harm to an individual in need of mental health services and those around them.</p>
<div class="cell" data-tbl-align="center">
<div class="cell-output-display">
<div id="tbl-facilities" class="anchored">

<table>
<caption>Table&nbsp;3:  Facility Characteristics </caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> All </th>
   <th style="text-align:center;"> Count All </th>
   <th style="text-align:center;"> Inpatient </th>
   <th style="text-align:center;"> Count </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;background-color: #F4A5FA !important;"> Inpatient Services </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; "> 8.9% </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; border-right:1px solid;"> 21 </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; "> 100% </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; "> 21 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Outpatient Services </td>
   <td style="text-align:center;width: 5em; "> 86.8% </td>
   <td style="text-align:center;width: 5em; border-right:1px solid;"> 204 </td>
   <td style="text-align:center;width: 5em; "> 61.9% </td>
   <td style="text-align:center;width: 5em; "> 13 </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;"> Partial Hospitalization Services </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 15.3% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; border-right:1px solid;"> 36 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 85.7% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 18 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Residential Services </td>
   <td style="text-align:center;width: 5em; "> 12.8% </td>
   <td style="text-align:center;width: 5em; border-right:1px solid;"> 30 </td>
   <td style="text-align:center;width: 5em; "> 9.5% </td>
   <td style="text-align:center;width: 5em; "> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;"> Telehealth Services </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 34.5% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; border-right:1px solid;"> 81 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 23.8% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 5 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Serves Adults </td>
   <td style="text-align:center;width: 5em; "> 91.1% </td>
   <td style="text-align:center;width: 5em; border-right:1px solid;"> 214 </td>
   <td style="text-align:center;width: 5em; "> 100% </td>
   <td style="text-align:center;width: 5em; "> 21 </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #F4A5FA !important;"> Crisis Intervention </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; "> 35.3% </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; border-right:1px solid;"> 83 </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; "> 66.7% </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; "> 14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Walk-ins Accepted </td>
   <td style="text-align:center;width: 5em; "> 22.6% </td>
   <td style="text-align:center;width: 5em; border-right:1px solid;"> 53 </td>
   <td style="text-align:center;width: 5em; "> 76.2% </td>
   <td style="text-align:center;width: 5em; "> 16 </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;"> Federally Qualified Health Center </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 13.2% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; border-right:1px solid;"> 31 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 0.0% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Accepts Medicaid </td>
   <td style="text-align:center;width: 5em; "> 91.5% </td>
   <td style="text-align:center;width: 5em; border-right:1px solid;"> 215 </td>
   <td style="text-align:center;width: 5em; "> 100% </td>
   <td style="text-align:center;width: 5em; "> 21 </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #C09FF5 !important;"> Accepts Medicare </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 66.8% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; border-right:1px solid;"> 157 </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 100% </td>
   <td style="text-align:center;background-color: #C09FF5 !important;width: 5em; "> 21 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Accepts VA </td>
   <td style="text-align:center;width: 5em; "> 11.5% </td>
   <td style="text-align:center;width: 5em; border-right:1px solid;"> 27 </td>
   <td style="text-align:center;width: 5em; "> 33.3% </td>
   <td style="text-align:center;width: 5em; "> 7 </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #F4A5FA !important;"> Payment Assistance </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; "> 18.3% </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; border-right:1px solid;"> 43 </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; "> 19.0% </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 5em; "> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sliding Scale </td>
   <td style="text-align:center;width: 5em; "> 34.0% </td>
   <td style="text-align:center;width: 5em; border-right:1px solid;"> 80 </td>
   <td style="text-align:center;width: 5em; "> 14.3% </td>
   <td style="text-align:center;width: 5em; "> 3 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Of all facilities in Maryland, only 8.9%, or 21 facilities, offer inpatient care. <a href="#tbl-facilities">Table&nbsp;3</a> shows the frequency and percentages of various services and payment options. Most of these characteristics will not be covered in-depth in this report; the primary focus will be inpatient facilities with crisis intervention. The larger issue of inadequate mental health outpatient care and cost-prohibitive preventative care is another dimension of the story about the interactions of mental health and imprisonment that could also be explored with these data given the new variables available.</p>
<section id="overall" class="level2">
<h2 class="anchored" data-anchor-id="overall">Overall</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-map1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Imprisonment Rates and Mental Health Facilities</figcaption><p></p>
<p><img src="Facilities_wide.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>With this complete analytic dataset, visualizing the primary variables, imprisonment rate and inpatient mental health facilities, on a map provides some preliminary context for greater research questions. The map of imprisonment rates in Maryland, shown in <a href="#fig-map1">Figure&nbsp;1</a>, highlights the concentration of high imprisonment in the Baltimore urban area. Since Baltimore is the largest urban area entirely in Maryland, it is not unexpected to see higher rates of imprisonment in the city and surrounding areas. However, the suburbs of Washington, D.C. are also partially in Maryland with comparable population density, but the imprisonment rate for those areas are much lower than the Baltimore suburbs. Though rural areas outside of the two major metropolitan areas seem to have lower rates of imprisonment overall, the southeast peninsula and northwest panhandle seem to have surprisingly higher rates. From this <a href="@fig-map1">map</a>, it seems that these areas are further from inpatient facilities, and the few in those areas may not have sufficient capacity for the large areas they serve.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-MD" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Distribution of Imprisonment Rate by Race</figcaption><p></p>
<p><img src="Geography_of_Mass_Incarceration_files/figure-html/fig-MD-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>An initial overall look at the distribution of the tracts and imprisonment rate shows clear and obvious characteristics related to higher rates is race. <a href="#fig-MD">Figure&nbsp;2</a> clearly shows that census tracts that have a majority Black population have, on average, much higher rates of imprisonment. Tracts with less than a majority Black population had an average imprisonment rate of 162, and majority Black tracts had an average of 162, or 574 higher than their counterparts. While majority Black tracts had over 100 tracts with an imprisonment rate above 1,000 per 100,000 people, tracts without a majority Black population had only <em>eight</em> above 1,000 per 100,000 people, of which half were majority White (see <a href="#tbl-outliers">Table&nbsp;4</a>).</p>
<div class="cell" data-tbl-align="center">
<div class="cell-output-display">
<div id="tbl-outliers" class="anchored">

<table class=" lightable-classic" style="font-size: 13px; font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;"><caption>Table&nbsp;4:  Census Tracts Not Majority Black and Over 1000 Imprisoned per 100,000 </caption>
 <thead>
  <tr>
   <th style="text-align:center;"> FIPS </th>
   <th style="text-align:center;"> Tract </th>
   <th style="text-align:center;"> Imprisonment Rate </th>
   <th style="text-align:center;"> % White </th>
   <th style="text-align:center;"> % Black </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:center;"> 24043000400 </td>
   <td style="text-align:center;"> Washington County, Census Tract 4 </td>
   <td style="text-align:center;"> 1743 </td>
   <td style="text-align:center;"> 48.5 </td>
   <td style="text-align:center;"> 45.9 </td>
  </tr>
  <tr>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 24510250401 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> Baltimore City, Census Tract 2504.01 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 1263 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 57.7 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 29.2 </td>
  </tr>
  <tr>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 24510250303 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> Baltimore City, Census Tract 2503.03 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 1168 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 63.8 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 23.5 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 24510260404 </td>
   <td style="text-align:center;"> Baltimore City, Census Tract 2604.04 </td>
   <td style="text-align:center;"> 1139 </td>
   <td style="text-align:center;"> 48.8 </td>
   <td style="text-align:center;"> 13.1 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 24510250500 </td>
   <td style="text-align:center;"> Baltimore City, Census Tract 2505 </td>
   <td style="text-align:center;"> 1115 </td>
   <td style="text-align:center;"> 48.4 </td>
   <td style="text-align:center;"> 40.5 </td>
  </tr>
  <tr>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 24510060300 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> Baltimore City, Census Tract 603 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 1096 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 55.2 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 37.8 </td>
  </tr>
  <tr>
   <td style="text-align:center;"> 24510060200 </td>
   <td style="text-align:center;"> Baltimore City, Census Tract 602 </td>
   <td style="text-align:center;"> 1030 </td>
   <td style="text-align:center;"> 43.6 </td>
   <td style="text-align:center;"> 48.8 </td>
  </tr>
  <tr>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 24510030200 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> Baltimore City, Census Tract 302 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 1009 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 61.4 </td>
   <td style="text-align:center;background-color: #FFD1F9 !important;"> 26.6 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-tbl-align="center">
<div class="cell-output-display">
<div id="tbl-regress1" class="anchored">

<table class="table lightable-classic" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0; font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;"><caption>Table&nbsp;5:  Imprisonment and Key Characteristics: Maryland </caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> Model 1 </th>
   <th style="text-align:center;"> &nbsp;Model 2 </th>
   <th style="text-align:center;"> &nbsp;Model 3 </th>
   <th style="text-align:center;"> All </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 7em; "> (Intercept) </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 880.88*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 13.92 </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 465.84*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 260.55*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 7em; ">  </td>
   <td style="text-align:center;width: 5em; "> (32.80) </td>
   <td style="text-align:center;width: 5em; "> (0.91) </td>
   <td style="text-align:center;width: 5em; "> (14.67) </td>
   <td style="text-align:center;width: 5em; "> (7.13) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 7em; "> Median Income </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> −6.19*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> −4.09*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> −2.09*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 7em; ">  </td>
   <td style="text-align:center;width: 5em; "> (−23.42) </td>
   <td style="text-align:center;width: 5em; ">  </td>
   <td style="text-align:center;width: 5em; "> (−15.88) </td>
   <td style="text-align:center;width: 5em; "> (−6.11) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 7em; "> % Black </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 9.19*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 6.91*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 5.20*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 7em; ">  </td>
   <td style="text-align:center;width: 5em; ">  </td>
   <td style="text-align:center;width: 5em; "> (26.69) </td>
   <td style="text-align:center;width: 5em; "> (19.79) </td>
   <td style="text-align:center;width: 5em; "> (14.72) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 7em; "> % w/ Degree </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> −2.87*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 7em; ">  </td>
   <td style="text-align:center;width: 5em; ">  </td>
   <td style="text-align:center;width: 5em; ">  </td>
   <td style="text-align:center;width: 5em; ">  </td>
   <td style="text-align:center;width: 5em; "> (−4.21) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 7em; "> Unemployment </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 34.82*** </td>
  </tr>
  <tr>
   <td style="text-align:left;box-shadow: 0px 1pxwidth: 7em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 5em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 5em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 5em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 5em; "> (12.17) </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 7em; "> N </td>
   <td style="text-align:center;width: 5em; "> 1455 </td>
   <td style="text-align:center;width: 5em; "> 1455 </td>
   <td style="text-align:center;width: 5em; "> 1455 </td>
   <td style="text-align:center;width: 5em; "> 1455 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note: </span> <sup></sup> t statistics in parentheses <sup></sup> (+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001)</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>Expectedly, the common indicators of inequality have a significant relationship with imprisonment rates. Median income, percentage of Black people in the population, percentage of the population with at least a bachelor’s degree, and the unemployment rate are all strongly and significantly related to high imprisonment. As educational attainment and income rise, the expected imprisonment rate falls, and as the percentage of the population that is Black and the unemployment rate rises, so does the expected imprisonment rate. Even when controlling for all of these factors, each has a significant correlation with the rate of imprisonment (see <a href="#tbl-regress1">Table&nbsp;5</a>).</p>
<div class="cell" data-tbl-align="center">
<div class="cell-output-display">
<div id="tbl-regress2" class="anchored">

<table class="table lightable-classic" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0; font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;"><caption>Table&nbsp;6:  Imprisonment and Key Characteristics: Rural Maryland </caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> Model 1 </th>
   <th style="text-align:center;"> &nbsp;Model 2 </th>
   <th style="text-align:center;"> &nbsp;Model 3 </th>
   <th style="text-align:center;"> All </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 7em; "> (Intercept) </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 397.50*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 122.19*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 365.85*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 295.14*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 7em; ">  </td>
   <td style="text-align:center;width: 5em; "> (21.68) </td>
   <td style="text-align:center;width: 5em; "> (13.23) </td>
   <td style="text-align:center;width: 5em; "> (19.85) </td>
   <td style="text-align:center;width: 5em; "> (12.76) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 7em; "> Median Income </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> −2.39*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> −2.36*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> −1.31*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 7em; ">  </td>
   <td style="text-align:center;width: 5em; "> (−14.19) </td>
   <td style="text-align:center;width: 5em; ">  </td>
   <td style="text-align:center;width: 5em; "> (−14.53) </td>
   <td style="text-align:center;width: 5em; "> (−5.02) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 7em; "> % Black </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 1.86*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 1.74*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 1.46*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 7em; ">  </td>
   <td style="text-align:center;width: 5em; ">  </td>
   <td style="text-align:center;width: 5em; "> (5.36) </td>
   <td style="text-align:center;width: 5em; "> (6.03) </td>
   <td style="text-align:center;width: 5em; "> (5.19) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 7em; "> % w/ Degree </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> −2.13*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 7em; ">  </td>
   <td style="text-align:center;width: 5em; ">  </td>
   <td style="text-align:center;width: 5em; ">  </td>
   <td style="text-align:center;width: 5em; ">  </td>
   <td style="text-align:center;width: 5em; "> (−3.74) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 7em; "> Unemployment </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 5em; "> 11.21*** </td>
  </tr>
  <tr>
   <td style="text-align:left;box-shadow: 0px 1pxwidth: 7em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 5em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 5em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 5em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 5em; "> (5.05) </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 7em; "> N </td>
   <td style="text-align:center;width: 5em; "> 467 </td>
   <td style="text-align:center;width: 5em; "> 467 </td>
   <td style="text-align:center;width: 5em; "> 467 </td>
   <td style="text-align:center;width: 5em; "> 467 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note: </span> <sup></sup> t statistics in parentheses <sup></sup> (+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001)</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>Since Maryland does contain at least part of two major metropolitan areas, separating out the rural areas can provide insights into how relationships might change outside the city and how to plan and implement policies that target the needs of that type of community. However, <a href="#tbl-regress2">Table&nbsp;6</a> shows that the same tract characteristics are still significantly related to imprisonment rates, but with slightly lower numbers.</p>
<div class="cell" data-tbl-align="center">
<div class="cell-output-display">
<div id="tbl-regress3" class="anchored">

<table class="table lightable-classic" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0; font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;"><caption>Table&nbsp;7:  Distance to Mental Health Facilities (in Miles) </caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> All Maryland </th>
   <th style="text-align:center;"> Rural Model 1 </th>
   <th style="text-align:center;"> &nbsp;Rural Model 2 </th>
   <th style="text-align:center;"> &nbsp;Rural Model 3 </th>
   <th style="text-align:center;"> &nbsp;Rural Model 4 </th>
   <th style="text-align:center;"> All Rural Models </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 9.4em; "> (Intercept) </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> 458.54*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> 175.06*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> 121.96*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> 77.84*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> 97.47*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> 112.57*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 9.4em; ">  </td>
   <td style="text-align:center;width: 3.5em; "> (23.91) </td>
   <td style="text-align:center;width: 3.5em; "> (15.55) </td>
   <td style="text-align:center;width: 3.5em; "> (10.09) </td>
   <td style="text-align:center;width: 3.5em; "> (8.79) </td>
   <td style="text-align:center;width: 3.5em; "> (10.88) </td>
   <td style="text-align:center;width: 3.5em; "> (9.88) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 9.4em; "> Mental Health Facility </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> −10.50*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> −2.60** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> −4.47*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 9.4em; ">  </td>
   <td style="text-align:center;width: 3.5em; "> (−3.50) </td>
   <td style="text-align:center;width: 3.5em; "> (−2.61) </td>
   <td style="text-align:center;width: 3.5em; ">  </td>
   <td style="text-align:center;width: 3.5em; ">  </td>
   <td style="text-align:center;width: 3.5em; ">  </td>
   <td style="text-align:center;width: 3.5em; "> (−3.92) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 9.4em; "> Inpatient Facility </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> −13.51*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> 1.88** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> −0.22 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 9.4em; ">  </td>
   <td style="text-align:center;width: 3.5em; "> (−7.36) </td>
   <td style="text-align:center;width: 3.5em; ">  </td>
   <td style="text-align:center;width: 3.5em; "> (3.23) </td>
   <td style="text-align:center;width: 3.5em; ">  </td>
   <td style="text-align:center;width: 3.5em; ">  </td>
   <td style="text-align:center;width: 3.5em; "> (−0.31) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #F4A5FA !important;width: 9.4em; "> Inpatient with Crisis Intervention </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 3.5em; "> 0.62 </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 3.5em; "> 2.50*** </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 3.5em; "> 2.04*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 9.4em; ">  </td>
   <td style="text-align:center;width: 3.5em; "> (0.57) </td>
   <td style="text-align:center;width: 3.5em; ">  </td>
   <td style="text-align:center;width: 3.5em; ">  </td>
   <td style="text-align:center;width: 3.5em; "> (12.42) </td>
   <td style="text-align:center;width: 3.5em; ">  </td>
   <td style="text-align:center;width: 3.5em; "> (5.28) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 9.4em; "> Inpatient accepting Walk-ins </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> 2.12+ </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> 1.99*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 3.5em; "> 0.74* </td>
  </tr>
  <tr>
   <td style="text-align:left;box-shadow: 0px 1pxwidth: 9.4em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 3.5em; "> (1.90) </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 3.5em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 3.5em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 3.5em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 3.5em; "> (9.55) </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 3.5em; "> (2.00) </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 9.4em; "> N </td>
   <td style="text-align:center;width: 3.5em; "> 1455 </td>
   <td style="text-align:center;width: 3.5em; "> 467 </td>
   <td style="text-align:center;width: 3.5em; "> 467 </td>
   <td style="text-align:center;width: 3.5em; "> 467 </td>
   <td style="text-align:center;width: 3.5em; "> 467 </td>
   <td style="text-align:center;width: 3.5em; "> 467 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note: </span> <sup></sup> t statistics in parentheses <sup></sup> (+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001)</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>The crucial addition to this collection of census tract characteristics is the proximity to mental health facilities. As discussed earlier, access to mental health care, and specifically inpatient care when someone is in crisis, is not only an alternative to imprisonment, it may even prevent future harm and repair issues that can lead to criminal behavior. <a href="#tbl-regress3">Table&nbsp;7</a> shows little or even the opposite effect overall, but by isolating rural areas the relationship between distance and imprisonment is significant and positive, especially for inpatient facilities with crisis intervention or accepting walk-ins.</p>
<div class="cell" data-tbl-align="center">
<div class="cell-output-display">
<div id="tbl-regressALL" class="anchored">

<table class="table lightable-classic" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0; font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Table&nbsp;8:  All Models </caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> Maryland </th>
   <th style="text-align:center;"> Rural </th>
   <th style="text-align:center;"> Distance </th>
   <th style="text-align:center;"> Distance Rural </th>
   <th style="text-align:center;"> All Factors </th>
   <th style="text-align:center;"> All Rural </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 11em; "> (Intercept) </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 260.55*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 295.14*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 458.54*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 112.57*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 371.35*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 252.24*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (7.13) </td>
   <td style="text-align:center;width: 4.35em; "> (12.76) </td>
   <td style="text-align:center;width: 4.35em; "> (23.91) </td>
   <td style="text-align:center;width: 4.35em; "> (9.88) </td>
   <td style="text-align:center;width: 4.35em; "> (9.22) </td>
   <td style="text-align:center;width: 4.35em; "> (9.39) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #F4A5FA !important;width: 11em; "> Median Income </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> −2.09*** </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> −1.31*** </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> −2.05*** </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> −0.86*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (−6.11) </td>
   <td style="text-align:center;width: 4.35em; "> (−5.02) </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (−6.05) </td>
   <td style="text-align:center;width: 4.35em; "> (−3.37) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #F4A5FA !important;width: 11em; "> % Black </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> 5.20*** </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> 1.46*** </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> 5.27*** </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> 1.34*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (14.72) </td>
   <td style="text-align:center;width: 4.35em; "> (5.19) </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (14.43) </td>
   <td style="text-align:center;width: 4.35em; "> (4.98) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 11em; "> % w/ Degree </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −2.87*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −2.13*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −3.23*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −2.34*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (−4.21) </td>
   <td style="text-align:center;width: 4.35em; "> (−3.74) </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (−4.71) </td>
   <td style="text-align:center;width: 4.35em; "> (−4.44) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 11em; "> Unemployment </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 34.82*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 11.21*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 32.29*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 8.88*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (12.17) </td>
   <td style="text-align:center;width: 4.35em; "> (5.05) </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (11.63) </td>
   <td style="text-align:center;width: 4.35em; "> (4.24) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 11em; "> Mental Health Distance </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −10.50*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −4.47*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 8.97*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −2.75** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11em; ">  </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (−3.50) </td>
   <td style="text-align:center;width: 4.35em; "> (−3.92) </td>
   <td style="text-align:center;width: 4.35em; "> (3.88) </td>
   <td style="text-align:center;width: 4.35em; "> (−2.73) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 11em; "> Inpatient Distance </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −13.51*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −0.22 </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −13.69*** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −0.51 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11em; ">  </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (−7.36) </td>
   <td style="text-align:center;width: 4.35em; "> (−0.31) </td>
   <td style="text-align:center;width: 4.35em; "> (−10.32) </td>
   <td style="text-align:center;width: 4.35em; "> (−0.86) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #F4A5FA !important;width: 11em; "> Inpatient with Crisis Intervention Distance </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> 0.62 </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> 2.04*** </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> 3.66*** </td>
   <td style="text-align:center;background-color: #F4A5FA !important;width: 4.35em; "> 2.05*** </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11em; ">  </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; ">  </td>
   <td style="text-align:center;width: 4.35em; "> (0.57) </td>
   <td style="text-align:center;width: 4.35em; "> (5.28) </td>
   <td style="text-align:center;width: 4.35em; "> (4.58) </td>
   <td style="text-align:center;width: 4.35em; "> (6.29) </td>
  </tr>
  <tr>
   <td style="text-align:left;background-color: #BB98F5 !important;width: 11em; "> Inpatient accepting Walk-ins Distance </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; ">  </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 2.12+ </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> 0.74* </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −2.45** </td>
   <td style="text-align:center;background-color: #BB98F5 !important;width: 4.35em; "> −0.48 </td>
  </tr>
  <tr>
   <td style="text-align:left;box-shadow: 0px 1pxwidth: 11em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 4.35em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 4.35em; ">  </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 4.35em; "> (1.90) </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 4.35em; "> (2.00) </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 4.35em; "> (−3.00) </td>
   <td style="text-align:center;box-shadow: 0px 1pxwidth: 4.35em; "> (−1.46) </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11em; "> N </td>
   <td style="text-align:center;width: 4.35em; "> 1455 </td>
   <td style="text-align:center;width: 4.35em; "> 467 </td>
   <td style="text-align:center;width: 4.35em; "> 1455 </td>
   <td style="text-align:center;width: 4.35em; "> 467 </td>
   <td style="text-align:center;width: 4.35em; "> 1455 </td>
   <td style="text-align:center;width: 4.35em; "> 467 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note: </span> <sup></sup> t statistics in parentheses <sup></sup> (+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001)</td></tr></tfoot>
</table>

</div>
</div>
</div>
<p>Looking at all the models side-by-side in <a href="#tbl-regressALL">Table&nbsp;8</a>, even controlling for the tract characteristics from <a href="#tbl-regress1">Table&nbsp;5</a> and <a href="#tbl-regress2">Table&nbsp;6</a>, distance to facilities with crisis intervention has a significant relationship with imprisonment. Without accessibility to emergency mental health treatment, people in crisis are more likely to end up arrested, or worse, if police are the only option to de-escalate the situation.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-rural" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p></p><figcaption class="figure-caption">Figure&nbsp;3: Distance to Crisis Intervention from Rural Tracts</figcaption><p></p>
<p><img src="Geography_of_Mass_Incarceration_files/figure-html/fig-rural-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Because urban tracts are overrepresented and more likely to be spatially close to a facility, the relationship is not clear, However, this does not account for capacity at urban facilities. According to the <em>National Mental Health Services Survey (N-MHSS): 2020</em>, the average capacity of facilities across Maryland is 44 beds for inpatient clients (slightly lower than the national average of 49) <span class="citation" data-cites="samhsaNationalMentalHealth2020">(<a href="#ref-samhsaNationalMentalHealth2020" role="doc-biblioref">SAMHSA, 2020b</a>)</span>. Even assuming the facilities in Baltimore have a higher capacity than average, it is unlikely the four inpatient facilities within Baltimore City are equipped to adequately provide care to the city’s nearly half a million population. The map from <a href="#fig-map1">Figure&nbsp;1</a> highlights that Baltimore has the highest concentration of high imprisonment rates in Maryland, but few facilities offering inpatient care for a large and densely populated area.</p>
</section>
<section id="race-and-income" class="level2">
<h2 class="anchored" data-anchor-id="race-and-income">Race and Income</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-race1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p></p><figcaption class="figure-caption">Figure&nbsp;4: Income, Race, and Imprisonment Rate</figcaption><p></p>
<p><img src="Geography_of_Mass_Incarceration_files/figure-html/fig-race1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Throughout the state of Maryland, race and income are both strongly correlated with imprisonment rates. Race and income also have a strong relationship with each other. <a href="#fig-race1">Figure&nbsp;4</a> visualizes the relationship between income, race, and imprisonment; the vertical and horizontal lines indicate the median income and average imprisonment for tracts with a majority Black population and those without a majority (though not necessarily a majority White population). Almost all the tracts below the median income for tracts with a Black majority are above average for imprisonment. It is also notable that the median and mean for these variables are quite different for each group. Not only is the racial income disparity obvious, but that disparity can lead to higher rates of imprisonment, adding a huge obstacle to economic success in already struggling communities.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-map2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p></p><figcaption class="figure-caption">Figure&nbsp;5: Imprisonment Rates and Black Communities</figcaption><p></p>
<p><img src="Black_wide.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>While proximity to mental health care appears to be a bigger issue for rural areas, which may still be low-income but less likely to have a majority of Black residents, imprisonment is still an important issue in these communities. Especially in the Baltimore area, the percentage of Black residents is highly associated with high imprisonment. <a href="#fig-map2">Figure&nbsp;5</a> zooms in on two areas of Maryland with a high concentration of Black communities, the Washington D.C. suburbs and the Baltimore urban area. The darkest colors on the map indicate a high percentage of Black population and high imprisonment; the bright colors indicate that one is high but the other is low; the lightest colors indicate that both are low. In the D.C. suburbs there are some pockets that have high imprisonment, but many tracks with large Black populations, but relatively low imprisonment. However, in Baltimore, almost the entire area is high in both measures. It is worth investigating reasons the DC suburbs are not experiencing the level of imprisonment as in and around Baltimore, but that is outside the scope of this research.</p>
</section>
<section id="access-to-mental-health-care" class="level2">
<h2 class="anchored" data-anchor-id="access-to-mental-health-care">Access to Mental Health Care</h2>
<p>While Baltimore has the highest concentration of imprisonment, its tracts also have proximity to inpatient mental health facilities. However, there are only four facilities in Baltimore city. Though the exact capacity of these facilities is unknown, the average inpatient capacity for inpatient facilities in Maryland is, at most, 87 (or 25 excluding the only three facilities with a capacity of at least 100) <span class="citation" data-cites="samhsaNationalMentalHealth2020">(<a href="#ref-samhsaNationalMentalHealth2020" role="doc-biblioref">SAMHSA, 2020b</a>)</span>. The Baltimore area has over two million residents, and it is not likely that four facilities are sufficient to provide the necessary services for all those in need of care. In addition to other barriers, such as health insurance coverage and transportation to facilities, more research is needed to assess the most effective expansion of service to target the communities most in need.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-map3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p></p><figcaption class="figure-caption">Figure&nbsp;6: Distance to Inpatient Facilities with Crisis Intervention</figcaption><p></p>
<p><img src="Crisis_wide.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-MHF" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p></p><figcaption class="figure-caption">Figure&nbsp;7: Inpatient Accessibility</figcaption><p></p>
<p><img src="Geography_of_Mass_Incarceration_files/figure-html/fig-MHF-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Outside urban areas, distance to inpatient mental health facilities is significantly associated with imprisonment rates. <a href="#fig-map3">Figure&nbsp;6</a> shows the areas of Maryland with long travel times to inpatient facilities with crisis intervention and high imprisonment rates. As expected and explained earlier, the urban areas may be close and still have high imprisonment rates. But the southeast area has high travel times and high imprisonment but is not near a major city. This is an area where proximity is likely to play a larger role in accessibility and would be an area worth investing in more mental health resources. <a href="#fig-MHF">Figure&nbsp;7</a> plots the relationship between driving distance and imprisonment rate; the lighter lines indicate the means for tracts that are not majority White (the diamond points), and the darker lines indicate means for tracts with a majority White population (circle points). In rural tracts, proximity to inpatient care seems to lower imprisonment rates for non-majority white communities.</p>
<p>Proximity to mental health care can not only prevent harmful criminal behavior, but it can also serve as an alternative for dangerous situations before they become criminal actions. Untreated mental health issues can put someone in a crisis, and without the tools to respond to that crisis, the person suffering and others can be in danger. If the only resource available is the police, who may not even be trained or equipped to confront a person experiencing a mental health crisis, there is a higher chance that the situation will either harm the person in crisis, others, or both. No one calls an electrician when a toilet overflows, why would you want to call the police when you need a doctor? Either no one is called and the person may become desperate and turn to illegal activity, or the police are called and unable to de-escalate the situation resulting in arrest, incarceration, or even death.</p>
<p>Mental health accessibility is also important for formerly incarcerated people returning to their communities to heal from the trauma of imprisonment and become capable of reintegrating and supporting their community. Prison is a traumatizing place, and some people spend many years locked up for minor, non-violent offenses but endure years of violence and trauma from other inmates and staff, and they may be more in need of mental health care than ever before. Communities experiencing high rates of imprisonment need investment in mental health, not only for prevention, but for rehabilitation as well.</p>
</section>
</section>
<section id="discussion-and-conclusion" class="level1">
<h1>Discussion and Conclusion</h1>
<p>Discuss limitations, further research, and policy implications.</p>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<p>Data needed about capacity — Four inpatient facilities may be in close proximity to Baltimore residents, but capacity may be the issue in urban areas.</p>
</section>
<section id="further-research" class="level2">
<h2 class="anchored" data-anchor-id="further-research">Further Research</h2>
<p>Lack of health insurance for formerly imprisoned residents as a barrier to access mental health care.</p>
<section id="datasets" class="level3">
<h3 class="anchored" data-anchor-id="datasets">Datasets:</h3>
<ul>
<li>Maryland tracts with nearest facilities and <strong>all</strong> characteristics</li>
<li>Maryland tracts with nearest facilities and <strong>select</strong> characteristics</li>
<li>Maryland facilities list with <strong>all</strong> characteristics</li>
</ul>
</section>
</section>
<section id="policy-implications" class="level2">
<h2 class="anchored" data-anchor-id="policy-implications">Policy Implications</h2>
<p>Funding emergency mental health care to divert people in need of health care away from the carceral system both through prevention and treatment.</p>
<p>Many violent conflicts require de-escalation and treatment, not confinement.</p>
<p>Funding and supporting mental health care accessibility can enable people to receive the health care and resources they need instead of becoming entrenched in the endless cycle of incarceration and harm from the Prison Industrial Complex and all its extremities.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="appendix" class="level1">
<h1>Appendix</h1>
<section id="r-code" class="level2">
<h2 class="anchored" data-anchor-id="r-code">R Code</h2>
<div style="page-break-after: always;"></div>
</section>
<section id="excel-formulas" class="level2">
<h2 class="anchored" data-anchor-id="excel-formulas">Excel Formulas</h2>
<p><strong>Formula to test the accuracy of the imprisonment calculations:</strong><br>
<code>=IF(E2-D2=C2,TRUE,FALSE)</code></p>
<p><strong>Formula to calculate total population:</strong><br>
<code>=C2+D2</code></p>
<p><strong>Formula to test the accuracy of the imprisonment calculations:</strong><br>
<code>=IF(ROUND((C2/E2)*100000,0)=F2,TRUE,FALSE)</code></p>
<p><strong>Formula to calculate corrected imprisonment rates:</strong><br>
<code>=ROUND((C2/E2)*100000,0)</code></p>
<p><strong>Formula to parse out the facility name:</strong><br>
<code>=LEFT(A2, MIN(FIND(REGEXEXTRACT(A2, "\d"),A2))-1)</code></p>
<p><strong>Formula to parse out the facility address:</strong><br>
<code>=REGEXEXTRACT(A2,"[0-9]+ .+, [A-Z][a-z]+ [0-9]{5}")</code></p>
<p><strong>Formula to create dummy variables for services codes:</strong><br>
<code>=COUNTIF(INDEX(data2!$A:$DC, MATCH(data!$B2, data2!$B:$B, 0), 0), data!D$1)</code></p>
<div style="page-break-after: always;"></div>
</section>
<section id="arcgis-pro-log" class="level2">
<h2 class="anchored" data-anchor-id="arcgis-pro-log">ArcGIS Pro Log</h2>
<p><strong>Export Table</strong><br>
Input Table - MD.csv<br>
Output Table - MD_ExportTable</p>
<p><strong>Export Table</strong><br>
Input Table - MD_counties.csv<br>
Output Table - MD_counties_ExportTable</p>
<p><strong>Export Table</strong><br>
Input Table - Facilities.csv<br>
Output Table - Facilities_ExportTable</p>
<p><strong>Geocode Addresses</strong><br>
Input Table - Facilities_ExportTable<br>
Input Address Locator - https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/Esri World Geocoder<br>
Input Address Fields - ‘Single Line Input’ Address VISIBLE NONE<br>
Output Feature Class - Facilities_Geocode<br>
Dynamic Output Feature Class - STATIC<br>
Country - US<br>
Preferred Location Type - ADDRESS_LOCATION<br>
Output Fields - ALL</p>
<p><strong>Export Features</strong><br>
Input Features - <code>ACS Context for Emergency Response - Boundaries\Tract</code><br>
Output Feature Class - ACS_Tract</p>
<p><strong>Calculate Field</strong><br>
Input Table - ACS_Tract<br>
Field Name - FIPS<br>
Expression - <code>!GEOID!*1</code><br>
Expression Type - PYTHON3</p>
<p><strong>Add Join</strong><br>
Input Table - ACS_Tract<br>
Input Join Field - FIPS<br>
Join Table - MD_ExportTable<br>
Join Table Field - FIPS<br>
Keep All Target Features - KEEP_ALL<br>
Updated Input Layer or Table View - ACS_Tract_ExportFeatures<br>
Index Joined Fields - NO_INDEX_JOIN_FIELDS</p>
<p><strong>Export Features</strong><br>
Input Table - ACS_Tract<br>
Output Table - MD</p>
<p><strong>Project</strong><br>
Input Dataset or Feature Class - Facilities_Geocode<br>
Output Dataset or Feature Class - Facilities_MDSP<br>
Output Coordinate System - <code>PROJCS["NAD_1983_StatePlane_Maryland_FIPS_1900_Feet",</code><br>
<code>GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",</code><br>
<code>SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],</code><br>
<code>UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],</code><br>
<code>PARAMETER["False_Easting",1312333.333333333],PARAMETER["False_Northing",0.0],</code><br>
<code>PARAMETER["Central_Meridian",-77.0],PARAMETER["Standard_Parallel_1",38.3],</code><br>
<code>PARAMETER["Standard_Parallel_2",39.45],PARAMETER["Latitude_Of_Origin",37.66666666666666],</code><br>
<code>UNIT["Foot_US",0.3048006096012192]]</code><br>
Geographic Transformation - NAD_1983_To_WGS_1984_1<br>
Input Coordinate System - <code>GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",</code><br>
<code>SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],</code><br>
<code>UNIT["Degree",0.0174532925199433]]</code><br>
Preserve Shape - NO_PRESERVE_SHAPE<br>
Vertical - NO_VERTICAL</p>
<p><strong>Project</strong><br>
Input Dataset or Feature Class - County Boundaries<br>
Output Dataset or Feature Class - County_Boundaries_MDSP<br>
Output Coordinate System - <code>PROJCS["NAD_1983_StatePlane_Maryland_FIPS_1900_Feet",</code><br>
<code>GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",</code><br>
<code>SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],</code><br>
<code>UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],</code><br>
<code>PARAMETER["False_Easting",1312333.333333333],PARAMETER["False_Northing",0.0],</code><br>
<code>PARAMETER["Central_Meridian",-77.0],PARAMETER["Standard_Parallel_1",38.3],</code><br>
<code>PARAMETER["Standard_Parallel_2",39.45],PARAMETER["Latitude_Of_Origin",37.66666666666666],</code><br>
<code>UNIT["Foot_US",0.3048006096012192]]</code><br>
Geographic Transformation - NAD_1983_To_WGS_1984_1<br>
Input Coordinate System - <code>GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",</code><br>
<code>SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],</code><br>
<code>UNIT["Degree",0.0174532925199433]]</code><br>
Preserve Shape - NO_PRESERVE_SHAPE<br>
Vertical - NO_VERTICAL</p>
<p><strong>Project</strong><br>
Input Dataset or Feature Class - MD<br>
Output Dataset or Feature Class - MD_MDSP<br>
Output Coordinate System - <code>PROJCS["NAD_1983_StatePlane_Maryland_FIPS_1900_Feet",</code><br>
<code>GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",</code><br>
<code>SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],</code><br>
<code>UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],</code><br>
<code>PARAMETER["False_Easting",1312333.333333333],PARAMETER["False_Northing",0.0],</code><br>
<code>PARAMETER["Central_Meridian",-77.0],PARAMETER["Standard_Parallel_1",38.3],</code><br>
<code>PARAMETER["Standard_Parallel_2",39.45],PARAMETER["Latitude_Of_Origin",37.66666666666666],</code><br>
<code>UNIT["Foot_US",0.3048006096012192]]</code><br>
Geographic Transformation - NAD_1983_To_WGS_1984_1<br>
Input Coordinate System - <code>GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",</code><br>
<code>SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],</code><br>
<code>UNIT["Degree",0.0174532925199433]]</code> Preserve Shape - NO_PRESERVE_SHAPE<br>
Vertical - NO_VERTICAL</p>
<p><strong>Select Layer By Attribute</strong><br>
Input Rows - Facilities_MDSP<br>
Selection Type - NEW_SELECTION<br>
Expression - <code>USER_VeteransOnly = 0</code><br>
Updated Layer Or Table View - Facilities_MDSP<br>
Count - 230</p>
<p><strong>Spatial Join</strong><br>
Target Features - MD_MDSP<br>
Join Features - Facilities_MDSP<br>
Output Feature Class - MD_MHF<br>
Join Operation - JOIN_ONE_TO_MANY<br>
Keep All Target Features - KEEP_ALL<br>
Match Option - CLOSEST<br>
Distance Field Name - MHF_distance</p>
<p><strong>Calculate Field</strong><br>
Input Table - MD_MHF<br>
Field Name - MHF_miles<br>
Expression - <code>!MHF_distance! / 5280</code><br>
Expression Type - PYTHON3</p>
<p><strong>Select Layer By Attribute</strong><br>
Input Rows - Facilities_MDSP<br>
Selection Type - NEW_SELECTION<br>
Expression - <code>USER_VeteransOnly = 0 And USER_Setting_Inpatient = 1</code><br>
Updated Layer Or Table View - Facilities_MDSP<br>
Count - 20</p>
<p><strong>Spatial Join</strong><br>
Target Features - MD_MHF<br>
Join Features - Facilities_MDSP<br>
Output Feature Class - MD_MHF_IH<br>
Join Operation - JOIN_ONE_TO_MANY<br>
Keep All Target Features - KEEP_ALL<br>
Match Option - CLOSEST<br>
Distance Field Name - Inpatient_distance</p>
<p><strong>Calculate Field</strong><br>
Input Table - MD_MHF_IH<br>
Field Name - Inpatient_miles<br>
Expression - <code>!Inpatient_distance! / 5280</code><br>
Expression Type - PYTHON3</p>
<p><strong>Select Layer By Attribute</strong><br>
Input Rows - Facilities_MDSP<br>
Selection Type - NEW_SELECTION<br>
Expression - <code>USER_VeteransOnly = 0 And USER_Setting_Inpatient = 1 And USER_Emer_CrisisIntervention = 1</code><br>
Updated Layer Or Table View - Facilities_MDSP<br>
Count - 13</p>
<p><strong>Spatial Join</strong><br>
Target Features - MD_MHF_IH<br>
Join Features - Facilities__MDSP<br>
Output Feature Class - MD_MHF_IH_Crisis<br>
Join Operation - JOIN_ONE_TO_MANY<br>
Keep All Target Features - KEEP_ALL<br>
Match Option - CLOSEST<br>
Distance Field Name - Crisis_distance</p>
<p><strong>Calculate Field</strong><br>
Input Table - MD_MHF_IH_Crisis<br>
Field Name - Crisis_miles<br>
Expression - <code>!Crisis_distance! / 5280</code><br>
Expression Type - PYTHON3</p>
<p><strong>Select Layer By Attribute</strong><br>
Input Rows - Facilities_MDSP<br>
Selection Type - NEW_SELECTION<br>
Expression - <code>USER_VeteransOnly = 0 And USER_Setting_Inpatient = 1 And USER_Emer_Walkins = 1</code><br>
Updated Layer Or Table View - Facilities_MDSP<br>
Count - 15</p>
<p><strong>Spatial Join</strong><br>
Target Features - MD_MHF_IH_Crisis<br>
Join Features - Facilities_MDSP<br>
Output Feature Class - MD_MHF_IH_Crisis_Walk<br>
Join Operation - JOIN_ONE_TO_MANY<br>
Keep All Target Features - KEEP_ALL<br>
Match Option - CLOSEST<br>
Distance Field Name - Walkin_distance</p>
<p><strong>Calculate Field</strong><br>
Input Table - MD_MHF_IH_Crisis_Walk<br>
Field Name - Walkin_miles<br>
Expression - <code>!Walkin_distance! / 5280</code><br>
Expression Type - PYTHON3</p>
<p><strong>Export Features</strong><br>
Input Features - MD_MHF_IH_Crisis_Walk<br>
Output Feature Class - MD<br>
Use Field Alias as Name - NOT_USE_ALIAS</p>
<p><strong>Export Table</strong><br>
Input Table - Urban_Rural.csv<br>
Output Table - Urban_Rural_ExportTable</p>
<p><strong>Calculate Field</strong><br>
Input Table - Urban_Rural_ExportTable<br>
Field Name - FIPS<br>
Expression - <code>!GEO_ID![-11:]</code><br>
Expression Type - PYTHON3</p>
<p><strong>Add Join</strong><br>
Input Table - tl_2010_24_tract10<br>
Input Join Field - GEOID10<br>
Join Table - Urban_Rural_ExportTable<br>
Join Table Field - FIPS<br>
Keep All Target Features - KEEP_ALL<br>
Updated Input Layer or Table View - tl_2010_24_tract10<br>
Index Joined Field - INDEX_JOIN_FIELDS</p>
<p><strong>Export Features</strong><br>
Input Features - tl_2010_24_tract10<br>
Output Feature Class - Urban_Rural2010<br>
Use Field Alias as Name - NOT_USE_ALIAS</p>
<p><strong>Apportion Polygon</strong><br>
Input Polygons - Urban_Rural2010<br>
Fields to Apportion - H002001;H002002;H002005;H002006<br>
Target Polygons - MD<br>
Output Feature Class - MD_ApportionPoly<br>
Apportion Method - AREA<br>
Weight Field - Total_Pop<br>
Maintain target geometry - MAINTAIN_GEOMETRIES</p>
<p><strong>Calculate Field</strong><br>
Input Table - MD_ApportionPoly<br>
Field Name - pctRural<br>
Expression - <code>(!H002005! / !H002001!) *100</code><br>
Expression Type - PYTHON3</p>
<p><strong>Select Layer By Attribute</strong><br>
Input Rows - Facilities_MDSP<br>
Selection Type - NEW_SELECTION<br>
Expression - <code>USER_VeteransOnly = 0 And USER_Setting_Inpatient = 1</code><br>
Updated Layer Or Table View - Facilities_MDSP<br>
Count - 20</p>
<p><strong>Make OD Cost Matrix Analysis Layer</strong><br>
Network Data Source - https://www.arcgis.com/<br>
Layer Name - Urban Tracts to Inpatient<br>
Travel Mode - Driving Time<br>
Number of Destinations to Find - 1 Time Zone - LOCAL_TIME_AT_LOCATIONS<br>
Line Shape - STRAIGHT_LINES<br>
Network Analyst Layer - Urban Tracts to Inpatient<br>
Ignore Invalid Locations at Solve Time - SKIP</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Urban Tracts to Inpatient<br>
Sub Layer - Origins<br>
Input Locations - MDurban_Points<br>
Field Mappings - Name FIPS<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Urban Tracts to Inpatient<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Urban Tracts to Inpatient<br>
Sub Layer - Destinations<br>
Input Locations - Facilities_MDSP<br>
Field Mappings - Name USER_FacilityName<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Urban Tracts to Inpatient<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Solve</strong><br>
Input Network Analysis Layer - Urban Tracts to Inpatient<br>
Ignore Invalid Locations - SKIP<br>
Terminate on Solve Error - TERMINATE<br>
Network Analyst Layer - Urban Tracts to Inpatient<br>
Solve Succeeded - true</p>
<p><strong>Export Features</strong><br>
Input Features - <code>Urban Tracts to Inpatient\Lines</code><br>
Output Feature Class - Urban_Lines_Inpatient<br>
Use Field Alias as Name - NOT_USE_ALIAS</p>
<p><strong>Calculate Field</strong><br>
Input Table - Urban_Lines_Inpatient<br>
Field Name - FIPS<br>
Expression - <code>!Name![:11]</code><br>
Expression Type - PYTHON3</p>
<p><strong>Delete Identical</strong><br>
Input Dataset - Urban_Lines_Inpatient<br>
Field(s) - FIPS<br>
XY Tolerance -<br>
Z Tolerance - 0<br>
Updated Input Dataset - Urban_Lines_Inpatient</p>
<p><strong>Make OD Cost Matrix Analysis Layer</strong><br>
Network Data Source - https://www.arcgis.com/<br>
Layer Name - Rural Tracts to Inpatient<br>
Travel Mode - Driving Time<br>
Number of Destinations to Find - 1 Time Zone - LOCAL_TIME_AT_LOCATIONS<br>
Line Shape - STRAIGHT_LINES<br>
Network Analyst Layer - Rural Tracts to Inpatient<br>
Ignore Invalid Locations at Solve Time - SKIP</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Rural Tracts to Inpatient<br>
Sub Layer - Origins<br>
Input Locations - MDrural_Points<br>
Field Mappings - Name FIPS<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Rural Tracts to Inpatient<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Rural Tracts to Inpatient<br>
Sub Layer - Destinations<br>
Input Locations - Facilities_MDSP<br>
Field Mappings - Name USER_FacilityName<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Rural Tracts to Inpatient<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Solve</strong><br>
Input Network Analysis Layer - Rural Tracts to Inpatient<br>
Ignore Invalid Locations - SKIP<br>
Terminate on Solve Error - TERMINATE<br>
Network Analyst Layer - Rural Tracts to Inpatient<br>
Solve Succeeded - true</p>
<p><strong>Export Features</strong><br>
Input Features - <code>Rural Tracts to Inpatient\Lines</code><br>
Output Feature Class - Rural_Lines_Inpatient<br>
Use Field Alias as Name - NOT_USE_ALIAS</p>
<p><strong>Calculate Field</strong><br>
Input Table - Rural_Lines_Inpatient<br>
Field Name - FIPS<br>
Expression - <code>!Name![:11]</code><br>
Expression Type - PYTHON3</p>
<p><strong>Delete Identical</strong><br>
Input Dataset - Rural_Lines_Inpatient<br>
Field(s) - FIPS<br>
XY Tolerance -<br>
Z Tolerance - 0<br>
Updated Input Dataset - Rural_Lines_Inpatient</p>
<p><strong>Append</strong><br>
Input Datasets - Rural_Lines_Inpatient<br>
Target Dataset - Urban_Lines_Inpatient<br>
Field Matching Type - TEST<br>
Updated Target Dataset - Urban_Lines_Inpatient</p>
<p><strong>Join Field</strong><br>
Input Table - MD_ApportionPoly<br>
Input Join Field - GEOID<br>
Join Table - Urban_Lines_Inpatient<br>
Join Table Field - FIPS<br>
Transfer Fields - Name;Total_TravelTime;Total_Miles<br>
Updated Input Table - MD_ApportionPoly<br>
Transfer Method - NOT_USE_FM</p>
<p><strong>Select Layer By Attribute</strong><br>
Input Rows - Facilities_MDSP<br>
Selection Type - NEW_SELECTION<br>
Expression - <code>USER_VeteransOnly = 0 And USER_Setting_Inpatient = 1 And USER_Emer_CrisisIntervention = 1</code><br>
Updated Layer Or Table View - Facilities_MDSP<br>
Count - 13</p>
<p><strong>Make OD Cost Matrix Analysis Layer</strong><br>
Network Data Source - https://www.arcgis.com/<br>
Layer Name - Urban Tracts to Crisis<br>
Travel Mode - Driving Time<br>
Number of Destinations to Find - 1 Time Zone - LOCAL_TIME_AT_LOCATIONS<br>
Line Shape - STRAIGHT_LINES<br>
Network Analyst Layer - Urban Tracts to Crisis<br>
Ignore Invalid Locations at Solve Time - SKIP</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Urban Tracts to Crisis<br>
Sub Layer - Origins<br>
Input Locations - MDurban_Points<br>
Field Mappings - Name FIPS<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Urban Tracts to Crisis<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Urban Tracts to Crisis<br>
Sub Layer - Destinations<br>
Input Locations - Facilities_MDSP<br>
Field Mappings - Name USER_FacilityName<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Urban Tracts to Crisis<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Solve</strong><br>
Input Network Analysis Layer - Urban Tracts to Crisis<br>
Ignore Invalid Locations - SKIP<br>
Terminate on Solve Error - TERMINATE<br>
Network Analyst Layer - Urban Tracts to Crisis<br>
Solve Succeeded - true</p>
<p><strong>Export Features</strong><br>
Input Features - <code>Urban Tracts to Crisis\Lines</code><br>
Output Feature Class - Urban_Lines_Crisis<br>
Use Field Alias as Name - NOT_USE_ALIAS</p>
<p><strong>Calculate Field</strong><br>
Input Table - Urban_Lines_Crisis<br>
Field Name - FIPS<br>
Expression - <code>!Name![:11]</code><br>
Expression Type - PYTHON3</p>
<p><strong>Delete Identical</strong><br>
Input Dataset - Urban_Lines_Crisis<br>
Field(s) - FIPS<br>
XY Tolerance -<br>
Z Tolerance - 0<br>
Updated Input Dataset - Urban_Lines_Crisis</p>
<p><strong>Make OD Cost Matrix Analysis Layer</strong><br>
Network Data Source - https://www.arcgis.com/<br>
Layer Name - Rural Tracts to Crisis<br>
Travel Mode - Driving Time<br>
Number of Destinations to Find - 1 Time Zone - LOCAL_TIME_AT_LOCATIONS<br>
Line Shape - STRAIGHT_LINES<br>
Network Analyst Layer - Rural Tracts to Crisis<br>
Ignore Invalid Locations at Solve Time - SKIP</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Rural Tracts to Crisis<br>
Sub Layer - Origins<br>
Input Locations - MDrural_Points<br>
Field Mappings - Name FIPS<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Rural Tracts to Crisis<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Rural Tracts to Crisis<br>
Sub Layer - Destinations<br>
Input Locations - Facilities_MDSP<br>
Field Mappings - Name USER_FacilityName<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Rural Tracts to Crisis<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Solve</strong><br>
Input Network Analysis Layer - Rural Tracts to Crisis<br>
Ignore Invalid Locations - SKIP<br>
Terminate on Solve Error - TERMINATE<br>
Network Analyst Layer - Rural Tracts to Crisis<br>
Solve Succeeded - true</p>
<p><strong>Export Features</strong><br>
Input Features - <code>Rural Tracts to Crisis\Lines</code><br>
Output Feature Class - Rural_Lines_Crisis<br>
Use Field Alias as Name - NOT_USE_ALIAS</p>
<p><strong>Calculate Field</strong><br>
Input Table - Rural_Lines_Crisis<br>
Field Name - FIPS<br>
Expression - <code>!Name![:11]</code><br>
Expression Type - PYTHON3</p>
<p><strong>Delete Identical</strong><br>
Input Dataset - Rural_Lines_Crisis<br>
Field(s) - FIPS<br>
XY Tolerance -<br>
Z Tolerance - 0<br>
Updated Input Dataset - Rural_Lines_Crisis</p>
<p><strong>Append</strong><br>
Input Datasets - Rural_Lines_Crisis<br>
Target Dataset - Urban_Lines_Crisis<br>
Field Matching Type - TEST<br>
Updated Target Dataset - Urban_Lines_Crisis</p>
<p><strong>Join Field</strong><br>
Input Table - MD_ApportionPoly<br>
Input Join Field - GEOID<br>
Join Table - Urban_Lines_Crisis<br>
Join Table Field - FIPS<br>
Transfer Fields - Name;Total_TravelTime;Total_Miles<br>
Updated Input Table - MD_ApportionPoly<br>
Transfer Method - NOT_USE_FM</p>
<p><strong>Select Layer By Attribute</strong><br>
Input Rows - Facilities_MDSP<br>
Selection Type - NEW_SELECTION<br>
Expression - <code>USER_VeteransOnly = 0</code><br>
Updated Layer Or Table View - Facilities_MDSP<br>
Count - 230</p>
<p><strong>Make OD Cost Matrix Analysis Layer</strong><br>
Network Data Source - https://www.arcgis.com/<br>
Layer Name - Urban Tracts to MHF<br>
Travel Mode - Driving Time<br>
Number of Destinations to Find - 1 Time Zone - LOCAL_TIME_AT_LOCATIONS<br>
Line Shape - STRAIGHT_LINES<br>
Network Analyst Layer - Urban Tracts to MHF<br>
Ignore Invalid Locations at Solve Time - SKIP</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Urban Tracts to MHF<br>
Sub Layer - Origins<br>
Input Locations - MDurban_Points<br>
Field Mappings - Name FIPS<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Urban Tracts to MHF<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Urban Tracts to MHF<br>
Sub Layer - Destinations<br>
Input Locations - Facilities_MDSP<br>
Field Mappings - Name USER_FacilityName<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Urban Tracts to MHF<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Solve</strong><br>
Input Network Analysis Layer - Urban Tracts to MHF<br>
Ignore Invalid Locations - SKIP<br>
Terminate on Solve Error - TERMINATE<br>
Network Analyst Layer - Urban Tracts to MHF<br>
Solve Succeeded - true</p>
<p><strong>Export Features</strong><br>
Input Features - <code>Urban Tracts to MHF\Lines</code><br>
Output Feature Class - Urban_Lines_MHF<br>
Use Field Alias as Name - NOT_USE_ALIAS</p>
<p><strong>Calculate Field</strong><br>
Input Table - Urban_Lines_MHF<br>
Field Name - FIPS<br>
Expression - <code>!Name![:11]</code><br>
Expression Type - PYTHON3</p>
<p><strong>Delete Identical</strong><br>
Input Dataset - Urban_Lines_MHF<br>
Field(s) - FIPS<br>
XY Tolerance -<br>
Z Tolerance - 0<br>
Updated Input Dataset - Urban_Lines_MHF</p>
<p><strong>Make OD Cost Matrix Analysis Layer</strong><br>
Network Data Source - https://www.arcgis.com/<br>
Layer Name - Rural Tracts to MHF<br>
Travel Mode - Driving Time<br>
Number of Destinations to Find - 1 Time Zone - LOCAL_TIME_AT_LOCATIONS<br>
Line Shape - STRAIGHT_LINES<br>
Network Analyst Layer - Rural Tracts to MHF<br>
Ignore Invalid Locations at Solve Time - SKIP</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Rural Tracts to MHF<br>
Sub Layer - Origins<br>
Input Locations - MDrural_Points<br>
Field Mappings - Name FIPS<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Rural Tracts to MHF<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Rural Tracts to MHF<br>
Sub Layer - Destinations<br>
Input Locations - Facilities_MDSP<br>
Field Mappings - Name USER_FacilityName<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Rural Tracts to MHF<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Solve</strong><br>
Input Network Analysis Layer - Rural Tracts to MHF<br>
Ignore Invalid Locations - SKIP<br>
Terminate on Solve Error - TERMINATE<br>
Network Analyst Layer - Rural Tracts to MHF<br>
Solve Succeeded - true</p>
<p><strong>Export Features</strong><br>
Input Features - <code>Rural Tracts to MHF\Lines</code><br>
Output Feature Class - Rural_Lines_MHF<br>
Use Field Alias as Name - NOT_USE_ALIAS</p>
<p><strong>Calculate Field</strong><br>
Input Table - Rural_Lines_MHF<br>
Field Name - FIPS<br>
Expression - <code>!Name![:11]</code><br>
Expression Type - PYTHON3</p>
<p><strong>Delete Identical</strong><br>
Input Dataset - Rural_Lines_MHF<br>
Field(s) - FIPS<br>
XY Tolerance -<br>
Z Tolerance - 0<br>
Updated Input Dataset - Rural_Lines_MHF</p>
<p><strong>Append</strong><br>
Input Datasets - Rural_Lines_MHF<br>
Target Dataset - Urban_Lines_MHF<br>
Field Matching Type - TEST<br>
Updated Target Dataset - Urban_Lines_MHF</p>
<p><strong>Join Field</strong><br>
Input Table - MD_ApportionPoly<br>
Input Join Field - GEOID<br>
Join Table - Urban_Lines_Walkin<br>
Join Table Field - FIPS<br>
Transfer Fields - Name;Total_TravelTime;Total_Miles<br>
Updated Input Table - MD_ApportionPoly<br>
Transfer Method - NOT_USE_FM</p>
<p><strong>Select Layer By Attribute</strong><br>
Input Rows - Facilities_MDSP<br>
Selection Type - NEW_SELECTION<br>
Expression - <code>USER_VeteransOnly = 0 And USER_Setting_Inpatient = 1 And USER_Emer_Walkins = 1</code><br>
Updated Layer Or Table View - Facilities_MDSP<br>
Count - 15</p>
<p><strong>Make OD Cost Matrix Analysis Layer</strong><br>
Network Data Source - https://www.arcgis.com/<br>
Layer Name - Urban Tracts to Walkin<br>
Travel Mode - Driving Time<br>
Number of Destinations to Find - 1 Time Zone - LOCAL_TIME_AT_LOCATIONS<br>
Line Shape - STRAIGHT_LINES<br>
Network Analyst Layer - Urban Tracts to Walkin<br>
Ignore Invalid Locations at Solve Time - SKIP</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Urban Tracts to Walkin<br>
Sub Layer - Origins<br>
Input Locations - MDurban_Points<br>
Field Mappings - Name FIPS<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Urban Tracts to Walkin<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Urban Tracts to Walkin<br>
Sub Layer - Destinations<br>
Input Locations - Facilities_MDSP<br>
Field Mappings - Name USER_FacilityName<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Urban Tracts to Walkin<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Solve</strong><br>
Input Network Analysis Layer - Urban Tracts to Walkin<br>
Ignore Invalid Locations - SKIP<br>
Terminate on Solve Error - TERMINATE<br>
Network Analyst Layer - Urban Tracts to Walkin<br>
Solve Succeeded - true</p>
<p><strong>Export Features</strong><br>
Input Features - <code>Urban Tracts to Walkin\Lines</code><br>
Output Feature Class - Urban_Lines_Walkin<br>
Use Field Alias as Name - NOT_USE_ALIAS</p>
<p><strong>Calculate Field</strong><br>
Input Table - Urban_Lines_Walkin<br>
Field Name - FIPS<br>
Expression - <code>!Name![:11]</code><br>
Expression Type - PYTHON3</p>
<p><strong>Delete Identical</strong><br>
Input Dataset - Urban_Lines_Walkin<br>
Field(s) - FIPS<br>
XY Tolerance -<br>
Z Tolerance - 0<br>
Updated Input Dataset - Urban_Lines_Walkin</p>
<p><strong>Make OD Cost Matrix Analysis Layer</strong><br>
Network Data Source - https://www.arcgis.com/<br>
Layer Name - Rural Tracts to Walkin<br>
Travel Mode - Driving Time<br>
Number of Destinations to Find - 1 Time Zone - LOCAL_TIME_AT_LOCATIONS<br>
Line Shape - STRAIGHT_LINES<br>
Network Analyst Layer - Rural Tracts to Walkin<br>
Ignore Invalid Locations at Solve Time - SKIP</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Rural Tracts to Walkin<br>
Sub Layer - Origins<br>
Input Locations - MDrural_Points<br>
Field Mappings - Name FIPS<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Rural Tracts to Walkin<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Add Locations</strong><br>
Input Network Analysis Layer - Rural Tracts to Walkin<br>
Sub Layer - Destinations<br>
Input Locations - Facilities_MDSP<br>
Field Mappings - Name USER_FacilityName<br>
Search Tolerance - 20000 Meters<br>
Search Criteria - main.Routing_Streets SHAPE<br>
Find Closest among All Classes - MATCH_TO_CLOSEST<br>
Append to Existing Locations - APPEND<br>
Snap to Network - NO_SNAP<br>
Snap Offset - 5 Meters<br>
Exclude Restricted Portions of the Network - EXCLUDE<br>
Updated Input Network Analysis Layer - Rural Tracts to Walkin<br>
Allow automatic relocating at solve time - ALLOW</p>
<p><strong>Solve</strong><br>
Input Network Analysis Layer - Rural Tracts to Walkin<br>
Ignore Invalid Locations - SKIP<br>
Terminate on Solve Error - TERMINATE<br>
Network Analyst Layer - Rural Tracts to Walkin<br>
Solve Succeeded - true</p>
<p><strong>Export Features</strong><br>
Input Features - <code>Rural Tracts to Walkin\Lines</code><br>
Output Feature Class - Rural_Lines_Walkin<br>
Use Field Alias as Name - NOT_USE_ALIAS</p>
<p><strong>Calculate Field</strong><br>
Input Table - Rural_Lines_Walkin<br>
Field Name - FIPS<br>
Expression - <code>!Name![:11]</code><br>
Expression Type - PYTHON3</p>
<p><strong>Delete Identical</strong><br>
Input Dataset - Rural_Lines_Walkin<br>
Field(s) - FIPS<br>
XY Tolerance -<br>
Z Tolerance - 0<br>
Updated Input Dataset - Rural_Lines_Walkin</p>
<p><strong>Append</strong><br>
Input Datasets - Rural_Lines_Walkin<br>
Target Dataset - Urban_Lines_Walkin<br>
Field Matching Type - TEST<br>
Updated Target Dataset - Urban_Lines_Walkin</p>
<p><strong>Join Field</strong><br>
Input Table - MD_ApportionPoly<br>
Input Join Field - GEOID<br>
Join Table - Urban_Lines_Walkin<br>
Join Table Field - FIPS<br>
Transfer Fields - Name;Total_TravelTime;Total_Miles<br>
Updated Input Table - MD_ApportionPoly<br>
Transfer Method - NOT_USE_FM</p>
<p><strong>Export Table</strong><br>
Input Table - MD_ApportionPoly<br>
Output Table - MD_GIS<br>
Use Field Alias as Name - NOT_USE_ALIAS</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="references" class="level1">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="doc-bibliography">
<div id="ref-benvenisteWhatPrisonGerrymandering2022" class="csl-entry" role="doc-biblioentry">
Benveniste, A. (2022, October 31). <em>What <span>Is Prison Gerrymandering</span> and <span>How Does It Impact US Politics</span>?</em> <span>Teen Vogue</span>. <a href="https://www.teenvogue.com/story/what-is-prison-gerrymandering">https://www.teenvogue.com/story/what-is-prison-gerrymandering</a>
</div>
<div id="ref-brennanMajorMentalDisorders2000" class="csl-entry" role="doc-biblioentry">
Brennan, P. A., Mednick, S. A., &amp; Hodgins, S. (2000). Major <span>Mental Disorders</span> and <span>Criminal Violence</span> in a <span>Danish Birth Cohort</span>. <em>Archives of General Psychiatry</em>, <em>57</em>(5), 494–500. <a href="https://doi.org/10.1001/archpsyc.57.5.494">https://doi.org/10.1001/archpsyc.57.5.494</a>
</div>
<div id="ref-CensusBureauData2020" class="csl-entry" role="doc-biblioentry">
<em>Census <span>Bureau Data</span></em>. (2020). <a href="https://data.census.gov/">https://data.census.gov/</a>
</div>
<div id="ref-cloudLifeSupportPublic2014" class="csl-entry" role="doc-biblioentry">
Cloud, D. (2014). <em>On <span>Life Support</span>: <span>Public Health</span> in the <span>Age</span> of <span>Mass Incarceration</span></em>. <span>Vera Institute of Justice</span>. <a href="https://www.vera.org/publications/on-life-support-public-health-in-the-age-of-mass-incarceration">https://www.vera.org/publications/on-life-support-public-health-in-the-age-of-mass-incarceration</a>
</div>
<div id="ref-easonMassImprisonmentRuralUrban2017" class="csl-entry" role="doc-biblioentry">
Eason, J. M., Zucker, D., &amp; Wildeman, C. (2017). Mass <span>Imprisonment</span> across the <span>Rural-Urban Interface</span>. <em>The ANNALS of the American Academy of Political and Social Science</em>, <em>672</em>(1), 202–216. <a href="https://doi.org/10.1177/0002716217705357">https://doi.org/10.1177/0002716217705357</a>
</div>
<div id="ref-esriACSContextEmergency2020" class="csl-entry" role="doc-biblioentry">
Esri. (2020). <em><span>ACS Context</span> for <span>Emergency Response</span> - <span>Boundaries</span></em>. <a href="https://www.arcgis.com/sharing/rest/content/items/9b15b7ac4e2e4ef7b70ed53a205beff2">https://www.arcgis.com/sharing/rest/content/items/9b15b7ac4e2e4ef7b70ed53a205beff2</a>
</div>
<div id="ref-fensterHowManyStates2021" class="csl-entry" role="doc-biblioentry">
Fenster, A. (2021, October 16). <em>How many states have ended prison gerrymandering? <span>About</span> a dozen*!</em> <span>Prison Gerrymandering Project</span>. <a href="https://www.prisonersofthecensus.org/news/2021/10/26/state_count/">https://www.prisonersofthecensus.org/news/2021/10/26/state_count/</a>
</div>
<div id="ref-gilmoreGoldenGulagPrisons2007" class="csl-entry" role="doc-biblioentry">
Gilmore, R. W. (2007). <em>Golden <span>Gulag</span>: <span>Prisons</span>, <span>Surplus</span>, <span>Crisis</span>, and <span>Opposition</span> in <span>Globalizing California</span></em> (1st ed.). <span>University of California Press</span>. <a href="https://www.jstor.org/stable/10.1525/j.ctt5hjht8">https://www.jstor.org/stable/10.1525/j.ctt5hjht8</a>
</div>
<div id="ref-hatzenbuehlerCollateralDamageMass2015" class="csl-entry" role="doc-biblioentry">
Hatzenbuehler, M. L., Keyes, K., Hamilton, A., Uddin, M., &amp; Galea, S. (2015). The <span>Collateral Damage</span> of <span>Mass Incarceration</span>: <span>Risk</span> of <span>Psychiatric Morbidity Among Nonincarcerated Residents</span> of <span>High-Incarceration Neighborhoods</span>. <em>American Journal of Public Health</em>, <em>105</em>(1), 138–143. <a href="https://doi.org/10.2105/AJPH.2014.302184">https://doi.org/10.2105/AJPH.2014.302184</a>
</div>
<div id="ref-hodginsConsequencesConductDisorder2005" class="csl-entry" role="doc-biblioentry">
Hodgins, S., Tiihonen, J., &amp; Ross, D. (2005). The consequences of <span>Conduct Disorder</span> for males who develop schizophrenia: <span>Associations</span> with criminality, aggressive behavior, substance use, and psychiatric services. <em>Schizophrenia Research</em>, <em>78</em>(2), 323–335. <a href="https://doi.org/10.1016/j.schres.2005.05.021">https://doi.org/10.1016/j.schres.2005.05.021</a>
</div>
<div id="ref-hortonLaunchingNewMovement2007" class="csl-entry" role="doc-biblioentry">
Horton, R. (2007). Launching a new movement for mental health. <em>The Lancet</em>, <em>370</em>(9590), 806. <a href="https://doi.org/10.1016/S0140-6736(07)61243-4">https://doi.org/10.1016/S0140-6736(07)61243-4</a>
</div>
<div id="ref-LivingAtlasWorld" class="csl-entry" role="doc-biblioentry">
<em>Living <span>Atlas</span> of the <span>World</span></em>. (n.d.). Retrieved March 16, 2023, from <a href="https://livingatlas.arcgis.com/en/home/">https://livingatlas.arcgis.com/en/home/</a>
</div>
<div id="ref-nosratiEconomicDeclineIncarceration2019" class="csl-entry" role="doc-biblioentry">
Nosrati, E., Kang-Brown, J., Ash, M., McKee, M., Marmot, M., &amp; King, L. P. (2019). Economic decline, incarceration, and mortality from drug use disorders in the <span>USA</span> between 1983 and 2014: An observational analysis. <em>The Lancet Public Health</em>, <em>4</em>(7), e326–e333. <a href="https://doi.org/10.1016/S2468-2667(19)30104-5">https://doi.org/10.1016/S2468-2667(19)30104-5</a>
</div>
<div id="ref-petrasDevelopmentalEpidemiologicalCourses2008" class="csl-entry" role="doc-biblioentry">
Petras, H., Kellam, S. G., Brown, C. H., Muthén, B. O., Ialongo, N. S., &amp; Poduska, J. M. (2008). Developmental epidemiological courses leading to antisocial personality disorder and violent and criminal behavior: <span>Effects</span> by young adulthood of a universal preventive intervention in first- and second-grade classrooms. <em>Drug and Alcohol Dependence</em>, <em>95</em>, S45–S59. <a href="https://doi.org/10.1016/j.drugalcdep.2007.10.015">https://doi.org/10.1016/j.drugalcdep.2007.10.015</a>
</div>
<div id="ref-pettitMassImprisonmentLife2004" class="csl-entry" role="doc-biblioentry">
Pettit, B., &amp; Western, B. (2004). Mass <span>Imprisonment</span> and the <span>Life Course</span>: <span>Race</span> and <span>Class Inequality</span> in <span>U</span>.<span>S</span>. <span>Incarceration</span>. <em>American Sociological Review</em>, <em>69</em>(2), 151–169. <a href="https://doi.org/10.1177/000312240406900201">https://doi.org/10.1177/000312240406900201</a>
</div>
<div id="ref-princeNoHealthMental2007" class="csl-entry" role="doc-biblioentry">
Prince, M., Patel, V., Saxena, S., Maj, M., Maselko, J., Phillips, M. R., &amp; Rahman, A. (2007). No health without mental health. <em>The Lancet</em>, <em>370</em>(9590), 859–877. <a href="https://doi.org/10.1016/S0140-6736(07)61238-0">https://doi.org/10.1016/S0140-6736(07)61238-0</a>
</div>
<div id="ref-prisonpolicyinitiative" class="csl-entry" role="doc-biblioentry">
Prison Policy Initiative. (n.d.). <em>About</em>. Retrieved March 12, 2023, from <a href="https://www.prisonpolicy.org/about.html">https://www.prisonpolicy.org/about.html</a>
</div>
<div id="ref-quandtResearchRoundupIncarceration2021" class="csl-entry" role="doc-biblioentry">
Quandt, K. R., &amp; Jones, A. (2021). <em>Research <span>Roundup</span>: <span>Incarceration</span> can cause lasting damage to mental health</em>. <span>Prison Policy Initiative</span>. <a href="https://www.prisonpolicy.org/blog/2021/05/13/mentalhealthimpacts/">https://www.prisonpolicy.org/blog/2021/05/13/mentalhealthimpacts/</a>
</div>
<div id="ref-RedistrictingData2020" class="csl-entry" role="doc-biblioentry">
<em>Redistricting <span>Data</span></em>. (2020). <span>Maryland Citizens Redistricting Commission</span>. <a href="https://redistricting.maryland.gov/Pages/default.aspx">https://redistricting.maryland.gov/Pages/default.aspx</a>
</div>
<div id="ref-samhsaSubstanceAbuseMental" class="csl-entry" role="doc-biblioentry">
SAMHSA. (n.d.). <em>Substance <span>Abuse</span> and <span>Mental Health Services Administration</span></em>. <span>SAMHSA - The Substance Abuse Mental Health Services Administration</span>. Retrieved March 12, 2023, from <a href="https://www.samhsa.gov/node">https://www.samhsa.gov/node</a>
</div>
<div id="ref-samhsaNationalDirectoryMental2020" class="csl-entry" role="doc-biblioentry">
SAMHSA. (2020a). <em>National <span>Directory</span> of <span>Mental Health Treatment Facilities</span> 2020</em>. <span>Substance Abuse and Mental Health Services Administration</span>. <a href="https://www.samhsa.gov/data/sites/default/files/reports/rpt23266/National_Directory_MH_facilities.pdf">https://www.samhsa.gov/data/sites/default/files/reports/rpt23266/National_Directory_MH_facilities.pdf</a>
</div>
<div id="ref-samhsaNationalMentalHealth2020" class="csl-entry" role="doc-biblioentry">
SAMHSA. (2020b). <em>National <span>Mental Health Services Survey</span> (<span>N-MHSS</span>): 2020. <span>Data</span> on <span>Mental Health Treatment Facilities</span></em>. <span>Substance Abuse and Mental Health Services Administration</span>. <a href="https://www.samhsa.gov/data/sites/default/files/reports/rpt35336/2020_NMHSS_final.pdf">https://www.samhsa.gov/data/sites/default/files/reports/rpt35336/2020_NMHSS_final.pdf</a>
</div>
<div id="ref-saxenaResourcesMentalHealth2007" class="csl-entry" role="doc-biblioentry">
Saxena, S., Thornicroft, G., Knapp, M., &amp; Whiteford, H. (2007). Resources for mental health: Scarcity, inequity, and inefficiency. <em>The Lancet</em>, <em>370</em>(9590), 878–889. <a href="https://doi.org/10.1016/S0140-6736(07)61239-2">https://doi.org/10.1016/S0140-6736(07)61239-2</a>
</div>
<div id="ref-sharkeyStuckPlaceUrban2013" class="csl-entry" role="doc-biblioentry">
Sharkey, P. (2013). <em>Stuck in <span>Place</span>: <span>Urban Neighborhoods</span> and the <span>End</span> of <span>Progress Toward Racial Equality</span></em>. <span>University of Chicago Press</span>. <a href="https://press.uchicago.edu/ucp/books/book/chicago/S/bo14365260.html">https://press.uchicago.edu/ucp/books/book/chicago/S/bo14365260.html</a>
</div>
<div id="ref-simesPunishingPlacesGeography2021" class="csl-entry" role="doc-biblioentry">
Simes, J. T. (2021). <em>Punishing <span>Places</span>: <span>The Geography</span> of <span>Mass Imprisonment</span></em>. <span>Univ of California Press</span>. <a href="https://books.google.com?id=jk8_EAAAQBAJ">https://books.google.com?id=jk8_EAAAQBAJ</a>
</div>
<div id="ref-thejusticepolicyinstituteCensusTractAppendix2023" class="csl-entry" role="doc-biblioentry">
The Justice Policy Institute, &amp; Prison Policy Initiative. (2023). <em>Census <span>Tract Appendix</span> - <span>Where</span> people in prison come from - <span>Maryland</span> (2020)</em>. <span>Prison Policy Initiative</span>. <a href="https://www.prisonpolicy.org/origin/md/2020/tract.html">https://www.prisonpolicy.org/origin/md/2020/tract.html</a>
</div>
<div id="ref-uscensusbureau2020CensusResidence2018" class="csl-entry" role="doc-biblioentry">
US Census Bureau. (2018). <em>2020 <span>Census Residence Criteria</span> and <span>Residence Situations</span></em>. <span>US Census Bureau</span>. <a href="https://www2.census.gov/programs-surveys/decennial/2020/program-management/memo-series/2020-memo-2018_04-appendix.pdf">https://www2.census.gov/programs-surveys/decennial/2020/program-management/memo-series/2020-memo-2018_04-appendix.pdf</a>
</div>
<div id="ref-wangBothSidesBars2022" class="csl-entry" role="doc-biblioentry">
Wang, L. (2022). <em>Both sides of the bars: <span>How</span> mass incarceration punishes families</em>. <span>Prison Policy Initiative</span>. <a href="https://www.prisonpolicy.org/blog/2022/08/11/parental_incarceration/">https://www.prisonpolicy.org/blog/2022/08/11/parental_incarceration/</a>
</div>
<div id="ref-widraWherePeoplePrison2023" class="csl-entry" role="doc-biblioentry">
Widra, E. (2023). <em>Where people in prison come from: <span>The</span> geography of mass incarceration</em>. <span>Prison Policy Initiative</span>. <a href="https://www.prisonpolicy.org/origin/2020report.html">https://www.prisonpolicy.org/origin/2020report.html</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>